"""
Seed script: populates the database with 50+ classic living books,
sources (vendors), book links, and curated lists.

Usage:
    cd backend
    python -m scripts.seed
"""

import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import text
from app.core.database import async_session, engine, Base
from app.models.book import Book, BookLink, Source
from app.models.list import CuratedList, ListItem


BOOKS = [
    {
        "title": "Carry On, Mr. Bowditch",
        "author": "Jean Lee Latham",
        "description": "The true story of Nathaniel Bowditch, a self-taught mathematical genius who revolutionized ocean navigation in the early days of American sailing.",
        "long_description": "This Newbery Medal winner brings to vivid life the incredible story of Nat Bowditch, who overcame poverty and lack of formal education to become one of America's greatest navigators. Through determination and a love of learning, young Nat taught himself mathematics, astronomy, and multiple languages, eventually writing The New American Practical Navigator — a book still used by sailors today.",
        "reading_level": "intermediate",
        "age_range": "10-14",
        "subjects": ["history", "biography", "mathematics", "science", "adventure"],
        "time_period": "18th century",
        "region": "North America",
        "isbn": "9780618250745",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 95,
        "page_count": 256,
        "publication_year": 1955,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Paddle-to-the-Sea",
        "author": "Holling C. Holling",
        "description": "A carved wooden canoe journeys from Lake Nipigon through the Great Lakes to the Atlantic Ocean, teaching geography through an unforgettable adventure.",
        "long_description": "An Indian boy carves a small canoe with a figure and sets it on a journey from a hilltop north of Lake Superior. Through ice, rapids, storms, and the industrialized waterways of the Great Lakes, the little canoe makes its way to the sea. With gorgeous full-color paintings and detailed marginal illustrations, this book is geography made living and beautiful.",
        "reading_level": "early-intermediate",
        "age_range": "6-12",
        "subjects": ["geography", "nature", "adventure"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780395292037",
        "language": "English",
        "awards": ["Caldecott Honor"],
        "popularity_score": 92,
        "page_count": 64,
        "publication_year": 1941,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "The Story of the World, Volume 1: Ancient Times",
        "author": "Susan Wise Bauer",
        "description": "History told as an engaging story from the earliest nomads through the fall of Rome, written specifically for young listeners and readers.",
        "reading_level": "read-aloud",
        "age_range": "5-10",
        "subjects": ["history", "ancient civilizations"],
        "time_period": "Ancient",
        "region": "World",
        "isbn": "9781933339009",
        "language": "English",
        "series": "Story of the World",
        "popularity_score": 98,
        "page_count": 362,
        "publication_year": 2006,
        "publisher": "Peace Hill Press",
    },
    {
        "title": "Charlotte's Web",
        "author": "E.B. White",
        "description": "The beloved tale of a pig named Wilbur and his devoted friend Charlotte, a wise spider who saves his life through her extraordinary weaving.",
        "long_description": "In this timeless classic, Fern saves a runt piglet and names him Wilbur. When Wilbur moves to the Zuckerman barn, he befriends Charlotte, a beautiful grey spider. When Wilbur's life is threatened, Charlotte weaves messages in her web to save him. A profound meditation on friendship, mortality, and the cycles of life — told with warmth, humor, and perfect simplicity.",
        "reading_level": "early-intermediate",
        "age_range": "6-10",
        "subjects": ["literature", "nature", "friendship"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780061124952",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 99,
        "page_count": 184,
        "publication_year": 1952,
        "publisher": "Harper & Brothers",
    },
    {
        "title": "Beautiful Stories from Shakespeare",
        "author": "E. Nesbit",
        "description": "Shakespeare's greatest plays retold as vivid, accessible stories for young readers by the masterful children's author E. Nesbit.",
        "reading_level": "intermediate",
        "age_range": "8-14",
        "subjects": ["literature", "drama", "classics"],
        "time_period": "Renaissance",
        "region": "Europe",
        "isbn": "9781514684474",
        "language": "English",
        "popularity_score": 78,
        "page_count": 180,
        "publication_year": 1907,
        "publisher": "Various",
    },
    {
        "title": "This Country of Ours",
        "author": "H.E. Marshall",
        "description": "American history from the Norse discoveries through the early 20th century, told as a gripping narrative that brings the past alive.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["history", "American history"],
        "time_period": "Multiple periods",
        "region": "North America",
        "isbn": "9781599152622",
        "language": "English",
        "popularity_score": 85,
        "page_count": 480,
        "publication_year": 1917,
        "publisher": "Yesterday's Classics",
    },
    {
        "title": "Understood Betsy",
        "author": "Dorothy Canfield Fisher",
        "description": "An over-protected city girl discovers independence, confidence, and the joy of learning when she goes to live with Vermont relatives.",
        "reading_level": "early-intermediate",
        "age_range": "7-11",
        "subjects": ["literature", "character", "farm life"],
        "time_period": "Early 20th century",
        "region": "North America",
        "isbn": "9780805005806",
        "language": "English",
        "popularity_score": 88,
        "page_count": 224,
        "publication_year": 1917,
        "publisher": "Henry Holt",
    },
    {
        "title": "The Wind in the Willows",
        "author": "Kenneth Grahame",
        "description": "The eternal story of Mole, Ratty, Badger, and the irrepressible Mr. Toad — a masterpiece of English literature bursting with nature and friendship.",
        "reading_level": "intermediate",
        "age_range": "7-12",
        "subjects": ["literature", "nature", "friendship", "classics"],
        "time_period": "Edwardian era",
        "region": "Europe",
        "isbn": "9780143039099",
        "language": "English",
        "popularity_score": 93,
        "page_count": 272,
        "publication_year": 1908,
        "publisher": "Methuen",
    },
    {
        "title": "Pilgrim's Progress",
        "author": "John Bunyan (retold by Mary Godolphin)",
        "description": "The allegorical masterpiece retold in simple one-syllable words, making this profound journey accessible to even young readers.",
        "reading_level": "early",
        "age_range": "6-10",
        "subjects": ["literature", "religion", "classics", "allegory"],
        "time_period": "17th century",
        "region": "Europe",
        "isbn": "9781882514502",
        "language": "English",
        "popularity_score": 76,
        "page_count": 128,
        "publication_year": 1884,
        "publisher": "Yesterday's Classics",
    },
    {
        "title": "Blueberries for Sal",
        "author": "Robert McCloskey",
        "description": "Little Sal and her mother pick blueberries on one side of Blueberry Hill while a bear and her cub eat on the other — with a delightful mix-up.",
        "reading_level": "early",
        "age_range": "3-7",
        "subjects": ["nature", "family", "picture book"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780140501698",
        "language": "English",
        "awards": ["Caldecott Honor"],
        "popularity_score": 90,
        "page_count": 56,
        "publication_year": 1948,
        "publisher": "Viking Press",
    },
    {
        "title": "The Burgess Bird Book for Children",
        "author": "Thornton W. Burgess",
        "description": "Through delightful stories of Peter Rabbit and his woodland friends, children learn to identify and appreciate dozens of North American birds.",
        "reading_level": "read-aloud",
        "age_range": "5-10",
        "subjects": ["nature", "science", "birds", "wildlife"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780486428406",
        "language": "English",
        "popularity_score": 82,
        "page_count": 336,
        "publication_year": 1919,
        "publisher": "Dover Publications",
    },
    {
        "title": "Little House in the Big Woods",
        "author": "Laura Ingalls Wilder",
        "description": "The first book in the beloved Little House series, bringing pioneer life in 1870s Wisconsin alive through the eyes of young Laura.",
        "reading_level": "early-intermediate",
        "age_range": "6-10",
        "subjects": ["history", "pioneer life", "family", "American frontier"],
        "time_period": "19th century",
        "region": "North America",
        "isbn": "9780064400015",
        "language": "English",
        "series": "Little House",
        "awards": ["Newbery Honor"],
        "popularity_score": 97,
        "page_count": 238,
        "publication_year": 1932,
        "publisher": "Harper & Brothers",
    },
    {
        "title": "Anne of Green Gables",
        "author": "L.M. Montgomery",
        "description": "Red-haired, imaginative orphan Anne Shirley transforms the lives of everyone in Avonlea with her irrepressible spirit and love of beauty.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["literature", "character", "family", "classics"],
        "time_period": "Late 19th century",
        "region": "Canada",
        "isbn": "9780141321592",
        "language": "English",
        "series": "Anne of Green Gables",
        "popularity_score": 96,
        "page_count": 320,
        "publication_year": 1908,
        "publisher": "L.C. Page & Co.",
    },
    {
        "title": "The Secret Garden",
        "author": "Frances Hodgson Burnett",
        "description": "A spoiled, neglected girl discovers a hidden garden and, through nurturing it back to life, heals herself and those around her.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["literature", "nature", "character", "classics"],
        "time_period": "Edwardian era",
        "region": "Europe",
        "isbn": "9780064401883",
        "language": "English",
        "popularity_score": 94,
        "page_count": 288,
        "publication_year": 1911,
        "publisher": "Frederick A. Stokes",
    },
    {
        "title": "Treasure Island",
        "author": "Robert Louis Stevenson",
        "description": "Young Jim Hawkins finds a treasure map and sails into the adventure of a lifetime with the cunning pirate Long John Silver.",
        "reading_level": "advanced",
        "age_range": "10-15",
        "subjects": ["literature", "adventure", "classics"],
        "time_period": "18th century",
        "region": "Europe",
        "isbn": "9780141321004",
        "language": "English",
        "popularity_score": 91,
        "page_count": 311,
        "publication_year": 1883,
        "publisher": "Cassell and Company",
    },
    {
        "title": "The Handbook of Nature Study",
        "author": "Anna Botsford Comstock",
        "description": "The indispensable guide for nature study — covering birds, insects, plants, rocks, and weather with detailed lessons and gorgeous illustrations.",
        "reading_level": "teacher-reference",
        "age_range": "6-adult",
        "subjects": ["nature", "science", "teacher resource"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780801493843",
        "language": "English",
        "popularity_score": 88,
        "page_count": 887,
        "publication_year": 1911,
        "publisher": "Comstock Publishing",
    },
    {
        "title": "A Child's Geography of the World",
        "author": "V.M. Hillyer",
        "description": "A conversational tour of the entire world that makes geography irresistibly fascinating for young minds.",
        "reading_level": "early-intermediate",
        "age_range": "6-10",
        "subjects": ["geography", "world cultures"],
        "time_period": "20th century",
        "region": "World",
        "isbn": "9781882514199",
        "language": "English",
        "series": "Calvert School",
        "popularity_score": 80,
        "page_count": 318,
        "publication_year": 1929,
        "publisher": "Yesterday's Classics",
    },
    {
        "title": "A Child's History of the World",
        "author": "V.M. Hillyer",
        "description": "World history told as one great story — from cavemen to the modern age — in a warm, conversational voice that captivates young listeners.",
        "reading_level": "read-aloud",
        "age_range": "6-10",
        "subjects": ["history", "world history"],
        "time_period": "Multiple periods",
        "region": "World",
        "isbn": "9781882514205",
        "language": "English",
        "series": "Calvert School",
        "popularity_score": 82,
        "page_count": 382,
        "publication_year": 1924,
        "publisher": "Yesterday's Classics",
    },
    {
        "title": "The Door in the Wall",
        "author": "Marguerite de Angeli",
        "description": "A crippled boy in medieval England discovers that courage and determination can open doors that seem forever closed.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["history", "medieval", "character", "disability"],
        "time_period": "Medieval",
        "region": "Europe",
        "isbn": "9780440402831",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 84,
        "page_count": 128,
        "publication_year": 1949,
        "publisher": "Doubleday",
    },
    {
        "title": "Island of the Blue Dolphins",
        "author": "Scott O'Dell",
        "description": "Based on a true story: a Native American girl survives alone for eighteen years on an island off the California coast.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["history", "survival", "nature", "Native American"],
        "time_period": "19th century",
        "region": "North America",
        "isbn": "9780547328614",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 90,
        "page_count": 192,
        "publication_year": 1960,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Number the Stars",
        "author": "Lois Lowry",
        "description": "Ten-year-old Annemarie must find the courage to help shelter her Jewish friend from the Nazis in occupied Copenhagen.",
        "reading_level": "intermediate",
        "age_range": "9-12",
        "subjects": ["history", "World War II", "courage", "friendship"],
        "time_period": "World War II",
        "region": "Europe",
        "isbn": "9780547577098",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 89,
        "page_count": 160,
        "publication_year": 1989,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Heidi",
        "author": "Johanna Spyri",
        "description": "A joyful orphan girl brought to live with her gruff grandfather in the Swiss Alps transforms everyone she meets with her innocent goodness.",
        "reading_level": "intermediate",
        "age_range": "7-12",
        "subjects": ["literature", "nature", "character", "classics"],
        "time_period": "19th century",
        "region": "Europe",
        "isbn": "9780140620986",
        "language": "English",
        "popularity_score": 91,
        "page_count": 352,
        "publication_year": 1881,
        "publisher": "Various",
    },
    {
        "title": "The Moffats",
        "author": "Eleanor Estes",
        "description": "Warm, funny, and utterly real stories of the four Moffat children growing up in a small Connecticut town during World War I.",
        "reading_level": "early-intermediate",
        "age_range": "7-11",
        "subjects": ["literature", "family", "humor"],
        "time_period": "World War I era",
        "region": "North America",
        "isbn": "9780152025359",
        "language": "English",
        "series": "The Moffats",
        "popularity_score": 79,
        "page_count": 304,
        "publication_year": 1941,
        "publisher": "Harcourt",
    },
    {
        "title": "Misty of Chincoteague",
        "author": "Marguerite Henry",
        "description": "Two children dream of owning a wild pony from the island of Chincoteague — based on the real annual pony penning tradition.",
        "reading_level": "early-intermediate",
        "age_range": "7-11",
        "subjects": ["nature", "animals", "adventure"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9781416927839",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 87,
        "page_count": 176,
        "publication_year": 1947,
        "publisher": "Rand McNally",
    },
    {
        "title": "Amos Fortune, Free Man",
        "author": "Elizabeth Yates",
        "description": "The true story of an African prince who was captured, enslaved, and eventually bought his freedom and the freedom of others in colonial New England.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["history", "biography", "slavery", "freedom", "character"],
        "time_period": "18th century",
        "region": "North America",
        "isbn": "9780140341584",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 83,
        "page_count": 192,
        "publication_year": 1950,
        "publisher": "Dutton",
    },
    {
        "title": "Rascal",
        "author": "Sterling North",
        "description": "A boy's year-long friendship with a mischievous baby raccoon in rural Wisconsin — one of the most charming nature memoirs ever written.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["nature", "animals", "memoir", "friendship"],
        "time_period": "World War I era",
        "region": "North America",
        "isbn": "9780140341454",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 81,
        "page_count": 189,
        "publication_year": 1963,
        "publisher": "Dutton",
    },
    {
        "title": "The Trumpeter of Krakow",
        "author": "Eric P. Kelly",
        "description": "A young boy and his family guard a priceless jewel in 15th-century Krakow while the boy takes up the ancient duty of the trumpeter.",
        "reading_level": "advanced",
        "age_range": "10-14",
        "subjects": ["history", "medieval", "adventure", "Poland"],
        "time_period": "15th century",
        "region": "Europe",
        "isbn": "9780689715716",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 75,
        "page_count": 208,
        "publication_year": 1928,
        "publisher": "Macmillan",
    },
    {
        "title": "D'Aulaires' Book of Greek Myths",
        "author": "Ingri and Edgar Parin d'Aulaire",
        "description": "The definitive introduction to Greek mythology for children, with magnificent lithograph illustrations and masterful retellings.",
        "reading_level": "early-intermediate",
        "age_range": "6-12",
        "subjects": ["mythology", "ancient Greece", "classics"],
        "time_period": "Ancient",
        "region": "Europe",
        "isbn": "9780440406945",
        "language": "English",
        "popularity_score": 94,
        "page_count": 192,
        "publication_year": 1962,
        "publisher": "Doubleday",
    },
    {
        "title": "The Story of Mankind",
        "author": "Hendrik Willem van Loon",
        "description": "The first Newbery Medal winner: a sweeping narrative of human civilization from prehistoric times to the modern era.",
        "reading_level": "advanced",
        "age_range": "10-15",
        "subjects": ["history", "world history", "civilization"],
        "time_period": "Multiple periods",
        "region": "World",
        "isbn": "9780871401540",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 77,
        "page_count": 480,
        "publication_year": 1921,
        "publisher": "Boni & Liveright",
    },
    {
        "title": "Pagoo",
        "author": "Holling C. Holling",
        "description": "The life cycle of a hermit crab explored through stunning illustrations and a narrative that makes marine biology unforgettable.",
        "reading_level": "early-intermediate",
        "age_range": "6-10",
        "subjects": ["nature", "science", "marine biology"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780395539644",
        "language": "English",
        "popularity_score": 80,
        "page_count": 88,
        "publication_year": 1957,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Tree in the Trail",
        "author": "Holling C. Holling",
        "description": "A cottonwood tree along the Santa Fe Trail witnesses two hundred years of American history from Native Americans to westward expansion.",
        "reading_level": "early-intermediate",
        "age_range": "7-12",
        "subjects": ["history", "nature", "American frontier", "geography"],
        "time_period": "Multiple periods",
        "region": "North America",
        "isbn": "9780395546826",
        "language": "English",
        "popularity_score": 81,
        "page_count": 64,
        "publication_year": 1942,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Minn of the Mississippi",
        "author": "Holling C. Holling",
        "description": "A snapping turtle's journey down the Mississippi River becomes a rich lesson in geography, natural history, and American culture.",
        "reading_level": "early-intermediate",
        "age_range": "7-12",
        "subjects": ["geography", "nature", "science"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780395273999",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 82,
        "page_count": 88,
        "publication_year": 1951,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Seabird",
        "author": "Holling C. Holling",
        "description": "A carved ivory gull accompanies four generations of seafarers from whaling ships to modern aircraft, tracing the evolution of transportation.",
        "reading_level": "early-intermediate",
        "age_range": "7-12",
        "subjects": ["history", "adventure", "maritime", "transportation"],
        "time_period": "Multiple periods",
        "region": "North America",
        "isbn": "9780395266816",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 79,
        "page_count": 64,
        "publication_year": 1948,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Robin Hood",
        "author": "Howard Pyle",
        "description": "The classic retelling of Robin Hood and his merry men in Sherwood Forest — swashbuckling adventure paired with Pyle's magnificent illustrations.",
        "reading_level": "advanced",
        "age_range": "10-15",
        "subjects": ["literature", "adventure", "medieval", "classics"],
        "time_period": "Medieval",
        "region": "Europe",
        "isbn": "9780486220437",
        "language": "English",
        "popularity_score": 86,
        "page_count": 312,
        "publication_year": 1883,
        "publisher": "Charles Scribner's Sons",
    },
    {
        "title": "King of the Wind",
        "author": "Marguerite Henry",
        "description": "The true story of the Godolphin Arabian, one of the three founding sires of the Thoroughbred breed, and his devoted mute stable boy.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["history", "animals", "biography"],
        "time_period": "18th century",
        "region": "Africa",
        "isbn": "9781416927860",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 83,
        "page_count": 176,
        "publication_year": 1948,
        "publisher": "Rand McNally",
    },
    {
        "title": "The Twenty-One Balloons",
        "author": "William Pène du Bois",
        "description": "Professor Sherman's hot-air balloon adventure leads him to the secret, fantastical civilization on the volcanic island of Krakatoa.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["adventure", "science", "humor", "invention"],
        "time_period": "19th century",
        "region": "Asia",
        "isbn": "9780140320978",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 82,
        "page_count": 180,
        "publication_year": 1947,
        "publisher": "Viking Press",
    },
    {
        "title": "Caddie Woodlawn",
        "author": "Carol Ryrie Brink",
        "description": "Based on her grandmother's stories, the adventures of a spirited tomboy growing up on the Wisconsin frontier in the 1860s.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["history", "pioneer life", "family", "American frontier"],
        "time_period": "19th century",
        "region": "North America",
        "isbn": "9781416940289",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 86,
        "page_count": 275,
        "publication_year": 1935,
        "publisher": "Macmillan",
    },
    {
        "title": "The Wheel on the School",
        "author": "Meindert DeJong",
        "description": "Six schoolchildren in a Dutch fishing village work together to bring the storks back to nest on their school roof.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["literature", "nature", "community", "Netherlands"],
        "time_period": "20th century",
        "region": "Europe",
        "isbn": "9780064402101",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 78,
        "page_count": 298,
        "publication_year": 1954,
        "publisher": "Harper",
    },
    {
        "title": "The Matchlock Gun",
        "author": "Walter D. Edmonds",
        "description": "A ten-year-old boy must defend his mother and baby sister with an ancient Spanish matchlock gun during a raid on their colonial home.",
        "reading_level": "early-intermediate",
        "age_range": "7-11",
        "subjects": ["history", "colonial America", "courage"],
        "time_period": "Colonial era",
        "region": "North America",
        "isbn": "9780698116801",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 74,
        "page_count": 64,
        "publication_year": 1941,
        "publisher": "Dodd, Mead",
    },
    {
        "title": "Watership Down",
        "author": "Richard Adams",
        "description": "A band of rabbits flee their doomed warren and embark on an epic journey to find a new home — a sweeping tale of courage, leadership, and myth.",
        "reading_level": "advanced",
        "age_range": "12-adult",
        "subjects": ["literature", "adventure", "nature", "leadership", "classics"],
        "time_period": "20th century",
        "region": "Europe",
        "isbn": "9780743277709",
        "language": "English",
        "awards": ["Carnegie Medal"],
        "popularity_score": 92,
        "page_count": 478,
        "publication_year": 1972,
        "publisher": "Rex Collings",
    },
    {
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "description": "Bilbo Baggins leaves his comfortable hobbit-hole and joins thirteen dwarves on a quest to reclaim their mountain home from a dragon.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["literature", "fantasy", "adventure", "classics"],
        "time_period": "Fantasy",
        "region": "Fantasy World",
        "isbn": "9780547928227",
        "language": "English",
        "popularity_score": 97,
        "page_count": 310,
        "publication_year": 1937,
        "publisher": "George Allen & Unwin",
    },
    {
        "title": "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        "author": "C.S. Lewis",
        "description": "Four children enter a magical world through a wardrobe and join the great lion Aslan in the battle against the White Witch's eternal winter.",
        "reading_level": "intermediate",
        "age_range": "8-13",
        "subjects": ["literature", "fantasy", "allegory", "classics"],
        "time_period": "Fantasy",
        "region": "Fantasy World",
        "isbn": "9780064471046",
        "language": "English",
        "series": "Chronicles of Narnia",
        "popularity_score": 98,
        "page_count": 208,
        "publication_year": 1950,
        "publisher": "Geoffrey Bles",
    },
    {
        "title": "A Wrinkle in Time",
        "author": "Madeleine L'Engle",
        "description": "Meg Murry, her brother Charles Wallace, and friend Calvin travel through a wrinkle in time to rescue her father from a dark force.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["literature", "science fiction", "family", "courage"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780312367541",
        "language": "English",
        "awards": ["Newbery Medal"],
        "series": "Time Quintet",
        "popularity_score": 93,
        "page_count": 256,
        "publication_year": 1962,
        "publisher": "Farrar, Straus and Giroux",
    },
    {
        "title": "Johnny Tremain",
        "author": "Esther Forbes",
        "description": "A young silversmith's apprentice in Boston becomes a key player in the events leading up to the American Revolution.",
        "reading_level": "intermediate",
        "age_range": "10-14",
        "subjects": ["history", "American Revolution", "coming of age"],
        "time_period": "18th century",
        "region": "North America",
        "isbn": "9780547614328",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 87,
        "page_count": 256,
        "publication_year": 1943,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Little Britches: Father and I Were Ranchers",
        "author": "Ralph Moody",
        "description": "A boy's adventures growing up on a Colorado ranch in the early 1900s — hardship, humor, and the making of character.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["memoir", "ranch life", "character", "American West"],
        "time_period": "Early 20th century",
        "region": "North America",
        "isbn": "9780803281783",
        "language": "English",
        "series": "Little Britches",
        "popularity_score": 88,
        "page_count": 260,
        "publication_year": 1950,
        "publisher": "W.W. Norton",
    },
    {
        "title": "The Good Master",
        "author": "Kate Seredy",
        "description": "A spirited city girl is sent to live on her uncle's ranch on the Hungarian plains, where she discovers a world of horses, folk traditions, and family.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["literature", "culture", "Hungary", "family", "horses"],
        "time_period": "Early 20th century",
        "region": "Europe",
        "isbn": "9780140301335",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 77,
        "page_count": 210,
        "publication_year": 1935,
        "publisher": "Viking Press",
    },
    {
        "title": "Where the Red Fern Grows",
        "author": "Wilson Rawls",
        "description": "A boy in the Ozarks saves for two coonhound pups and together they become the finest hunting team in the valley — a story of love, loyalty, and loss.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["literature", "nature", "animals", "coming of age"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780440412670",
        "language": "English",
        "popularity_score": 93,
        "page_count": 249,
        "publication_year": 1961,
        "publisher": "Doubleday",
    },
    {
        "title": "The Bronze Bow",
        "author": "Elizabeth George Speare",
        "description": "A young Jewish rebel in first-century Palestine is consumed by hatred of the Romans until he encounters Jesus of Nazareth.",
        "reading_level": "advanced",
        "age_range": "10-14",
        "subjects": ["history", "biblical era", "character", "religion"],
        "time_period": "Ancient",
        "region": "Middle East",
        "isbn": "9780395137192",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 82,
        "page_count": 254,
        "publication_year": 1961,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "The Witch of Blackbird Pond",
        "author": "Elizabeth George Speare",
        "description": "Kit Tyler, raised in tropical Barbados, struggles to fit into Puritan Connecticut — and her friendship with a Quaker woman leads to accusations of witchcraft.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["history", "colonial America", "character", "religious freedom"],
        "time_period": "Colonial era",
        "region": "North America",
        "isbn": "9780547550299",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 89,
        "page_count": 249,
        "publication_year": 1958,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Make Way for Ducklings",
        "author": "Robert McCloskey",
        "description": "Mr. and Mrs. Mallard search for the perfect place to raise their family in Boston — a joyful picture book classic.",
        "reading_level": "early",
        "age_range": "3-7",
        "subjects": ["nature", "picture book", "family"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780140564341",
        "language": "English",
        "awards": ["Caldecott Medal"],
        "popularity_score": 91,
        "page_count": 68,
        "publication_year": 1941,
        "publisher": "Viking Press",
    },
    {
        "title": "Ox-Cart Man",
        "author": "Donald Hall",
        "description": "The cycle of a New England farming family through the seasons — planting, harvesting, selling, and beginning again. Illustrated by Barbara Cooney.",
        "reading_level": "early",
        "age_range": "4-8",
        "subjects": ["history", "farm life", "picture book", "seasons"],
        "time_period": "19th century",
        "region": "North America",
        "isbn": "9780140504415",
        "language": "English",
        "awards": ["Caldecott Medal"],
        "popularity_score": 84,
        "page_count": 40,
        "publication_year": 1979,
        "publisher": "Viking Press",
    },
]

SOURCES = [
    {
        "name": "Amazon",
        "base_url": "https://www.amazon.com",
        "affiliate_tag": "livingbooks-20",
        "logo_url": "/images/sources/amazon.svg",
    },
    {
        "name": "BookShop.org",
        "base_url": "https://bookshop.org",
        "affiliate_tag": None,
        "logo_url": "/images/sources/bookshop.svg",
    },
    {
        "name": "ThriftBooks",
        "base_url": "https://www.thriftbooks.com",
        "affiliate_tag": None,
        "logo_url": "/images/sources/thriftbooks.svg",
    },
    {
        "name": "AbeBooks",
        "base_url": "https://www.abebooks.com",
        "affiliate_tag": None,
        "logo_url": "/images/sources/abebooks.svg",
    },
    {
        "name": "Library (WorldCat)",
        "base_url": "https://www.worldcat.org",
        "affiliate_tag": None,
        "logo_url": "/images/sources/library.svg",
    },
]

CURATED_LISTS = [
    {
        "name": "Charlotte Mason Essentials",
        "slug": "charlotte-mason-essentials",
        "description": "The living books most recommended by Charlotte Mason educators — books that bring subjects alive through literary storytelling rather than dry textbooks.",
        "category": "Philosophy",
        "is_featured": True,
        "book_titles": [
            "Charlotte's Web", "The Wind in the Willows", "Pilgrim's Progress",
            "The Handbook of Nature Study", "Understood Betsy", "Beautiful Stories from Shakespeare",
            "Paddle-to-the-Sea", "The Burgess Bird Book for Children",
        ],
    },
    {
        "name": "First Living Books (Ages 4-7)",
        "slug": "first-living-books",
        "description": "The perfect starting point for young children: picture books and read-alouds that spark wonder, imagination, and a love of learning.",
        "category": "By Age",
        "is_featured": True,
        "book_titles": [
            "Blueberries for Sal", "Make Way for Ducklings", "Ox-Cart Man",
            "Paddle-to-the-Sea", "The Burgess Bird Book for Children",
        ],
    },
    {
        "name": "Living History: Ancient World",
        "slug": "living-history-ancient",
        "description": "Travel back to ancient civilizations through stories that make history unforgettable — from Greek myths to biblical times.",
        "category": "History",
        "is_featured": True,
        "book_titles": [
            "The Story of the World, Volume 1: Ancient Times",
            "D'Aulaires' Book of Greek Myths", "The Bronze Bow",
            "The Story of Mankind",
        ],
    },
    {
        "name": "Living History: American Story",
        "slug": "living-history-america",
        "description": "Experience America's story through the eyes of those who lived it — from colonial days through the frontier and beyond.",
        "category": "History",
        "is_featured": True,
        "book_titles": [
            "Johnny Tremain", "Little House in the Big Woods", "Caddie Woodlawn",
            "The Witch of Blackbird Pond", "The Matchlock Gun", "Carry On, Mr. Bowditch",
            "This Country of Ours", "Amos Fortune, Free Man", "Little Britches: Father and I Were Ranchers",
        ],
    },
    {
        "name": "Nature Study Living Books",
        "slug": "nature-study",
        "description": "Books that cultivate a deep connection with the natural world — the foundation of Charlotte Mason's approach to science education.",
        "category": "Science & Nature",
        "is_featured": True,
        "book_titles": [
            "The Handbook of Nature Study", "The Burgess Bird Book for Children",
            "Pagoo", "Rascal", "Paddle-to-the-Sea", "Minn of the Mississippi",
            "Blueberries for Sal",
        ],
    },
    {
        "name": "Award Winners Hall of Fame",
        "slug": "award-winners",
        "description": "Newbery Medal and Honor winners that stand the test of time — books recognized as the finest in children's literature.",
        "category": "Awards",
        "is_featured": False,
        "book_titles": [
            "Carry On, Mr. Bowditch", "The Door in the Wall", "Island of the Blue Dolphins",
            "Number the Stars", "A Wrinkle in Time", "Johnny Tremain",
            "The Witch of Blackbird Pond", "The Bronze Bow", "The Wheel on the School",
            "King of the Wind", "Caddie Woodlawn",
        ],
    },
    {
        "name": "Adventure & Courage",
        "slug": "adventure-courage",
        "description": "Stories of bravery, perseverance, and daring that build character and ignite the imagination.",
        "category": "Character",
        "is_featured": False,
        "book_titles": [
            "Treasure Island", "Robin Hood", "The Hobbit",
            "Island of the Blue Dolphins", "Watership Down", "The Twenty-One Balloons",
            "Carry On, Mr. Bowditch",
        ],
    },
    {
        "name": "World Cultures & Geography",
        "slug": "world-cultures-geography",
        "description": "Living books that transport readers around the globe, building understanding and empathy for diverse peoples and places.",
        "category": "Geography",
        "is_featured": False,
        "book_titles": [
            "A Child's Geography of the World", "Heidi", "The Good Master",
            "The Wheel on the School", "The Trumpeter of Krakow",
            "Number the Stars", "King of the Wind",
        ],
    },
    {
        "name": "Timeless Fantasy & Imagination",
        "slug": "timeless-fantasy",
        "description": "The greatest fantasy and imaginative literature for young readers — stories that expand the mind and nourish the soul.",
        "category": "Literature",
        "is_featured": False,
        "book_titles": [
            "The Hobbit", "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
            "A Wrinkle in Time", "The Wind in the Willows", "Charlotte's Web",
            "Watership Down",
        ],
    },
    {
        "name": "Family Read-Alouds Everyone Loves",
        "slug": "family-read-alouds",
        "description": "The absolute best books for reading aloud together as a family — stories that captivate every age from 5 to 105.",
        "category": "Family",
        "is_featured": True,
        "book_titles": [
            "Charlotte's Web", "The Hobbit",
            "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
            "Little House in the Big Woods", "Where the Red Fern Grows",
            "Anne of Green Gables", "The Secret Garden", "The Wind in the Willows",
        ],
    },
]


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        # Check if already seeded
        from sqlalchemy import select, func
        count = (await session.execute(select(func.count(Book.id)))).scalar()
        if count and count > 0:
            print(f"Database already has {count} books. Skipping seed.")
            return

        # Insert books
        book_map = {}
        for data in BOOKS:
            book = Book(**data)
            session.add(book)
            await session.flush()
            book_map[data["title"]] = book.id
        print(f"Inserted {len(BOOKS)} books.")

        # Insert sources
        source_map = {}
        for data in SOURCES:
            source = Source(**data)
            session.add(source)
            await session.flush()
            source_map[data["name"]] = source.id
        print(f"Inserted {len(SOURCES)} sources.")

        # Create links for each book to Amazon and BookShop
        link_count = 0
        amazon_id = source_map["Amazon"]
        bookshop_id = source_map["BookShop.org"]
        thrift_id = source_map["ThriftBooks"]
        library_id = source_map["Library (WorldCat)"]

        for title, book_id in book_map.items():
            book_data = next(b for b in BOOKS if b["title"] == title)
            isbn = book_data.get("isbn", "")

            # Amazon link
            session.add(BookLink(
                book_id=book_id,
                source_id=amazon_id,
                url=f"https://www.amazon.com/dp/{isbn}?tag=livingbooks-20" if isbn else f"https://www.amazon.com/s?k={title.replace(' ', '+')}",
                link_type="buy",
                affiliate_tag="livingbooks-20",
                price_hint="$8-15",
            ))
            link_count += 1

            # Bookshop link
            session.add(BookLink(
                book_id=book_id,
                source_id=bookshop_id,
                url=f"https://bookshop.org/p/books/{isbn}" if isbn else f"https://bookshop.org/books?keywords={title.replace(' ', '+')}",
                link_type="buy",
                price_hint="$10-18",
            ))
            link_count += 1

            # ThriftBooks link
            session.add(BookLink(
                book_id=book_id,
                source_id=thrift_id,
                url=f"https://www.thriftbooks.com/w/{title.lower().replace(' ', '-')}/",
                link_type="buy",
                price_hint="$3-8",
            ))
            link_count += 1

            # Library link
            if isbn:
                session.add(BookLink(
                    book_id=book_id,
                    source_id=library_id,
                    url=f"https://www.worldcat.org/isbn/{isbn}",
                    link_type="rent",
                    price_hint="Free",
                ))
                link_count += 1

        print(f"Created {link_count} book links.")

        # Create curated lists
        for lst_data in CURATED_LISTS:
            book_titles = lst_data.pop("book_titles")
            lst = CuratedList(**lst_data)
            session.add(lst)
            await session.flush()

            for rank, bt in enumerate(book_titles, start=1):
                if bt in book_map:
                    session.add(ListItem(
                        list_id=lst.id,
                        book_id=book_map[bt],
                        rank=rank,
                    ))
            await session.flush()

        print(f"Created {len(CURATED_LISTS)} curated lists.")
        await session.commit()
        print("Seed complete!")


if __name__ == "__main__":
    asyncio.run(seed())
