"""
Seed script: populates the database with 50+ classic living books,
sources (vendors), book links, and curated lists.

Usage:
    cd backend
    python -m scripts.seed
"""

import asyncio
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import text
from app.core.database import async_session, engine, Base
from app.models.book import Book, BookLink, Source
from app.models.list import CuratedList, ListItem


BOOKS = [
    {
        "title": "Carry On, Mr. Bowditch",
        "author": "Jean Lee Latham",
        "description": "The true story of Nathaniel Bowditch, a self-taught mathematical genius who revolutionized ocean navigation in the early days of American sailing.",
        "long_description": "This Newbery Medal winner brings to vivid life the incredible story of Nat Bowditch, who overcame poverty and lack of formal education to become one of America's greatest navigators. Through determination and a love of learning, young Nat taught himself mathematics, astronomy, and multiple languages, eventually writing The New American Practical Navigator — a book still used by sailors today.",
        "reading_level": "intermediate",
        "age_range": "10-14",
        "subjects": ["history", "biography", "mathematics", "science", "adventure"],
        "time_period": "18th century",
        "region": "North America",
        "isbn": "9780618250745",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 95,
        "page_count": 256,
        "publication_year": 1955,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Paddle-to-the-Sea",
        "author": "Holling C. Holling",
        "description": "A carved wooden canoe journeys from Lake Nipigon through the Great Lakes to the Atlantic Ocean, teaching geography through an unforgettable adventure.",
        "long_description": "An Indian boy carves a small canoe with a figure and sets it on a journey from a hilltop north of Lake Superior. Through ice, rapids, storms, and the industrialized waterways of the Great Lakes, the little canoe makes its way to the sea. With gorgeous full-color paintings and detailed marginal illustrations, this book is geography made living and beautiful.",
        "reading_level": "early-intermediate",
        "age_range": "6-12",
        "subjects": ["geography", "nature", "adventure"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780395292037",
        "language": "English",
        "awards": ["Caldecott Honor"],
        "popularity_score": 92,
        "page_count": 64,
        "publication_year": 1941,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "The Story of the World, Volume 1: Ancient Times",
        "author": "Susan Wise Bauer",
        "description": "History told as an engaging story from the earliest nomads through the fall of Rome, written specifically for young listeners and readers.",
        "reading_level": "read-aloud",
        "age_range": "5-10",
        "subjects": ["history", "ancient civilizations"],
        "time_period": "Ancient",
        "region": "World",
        "isbn": "9781933339009",
        "language": "English",
        "series": "Story of the World",
        "popularity_score": 98,
        "page_count": 362,
        "publication_year": 2006,
        "publisher": "Peace Hill Press",
    },
    {
        "title": "Charlotte's Web",
        "author": "E.B. White",
        "description": "The beloved tale of a pig named Wilbur and his devoted friend Charlotte, a wise spider who saves his life through her extraordinary weaving.",
        "long_description": "In this timeless classic, Fern saves a runt piglet and names him Wilbur. When Wilbur moves to the Zuckerman barn, he befriends Charlotte, a beautiful grey spider. When Wilbur's life is threatened, Charlotte weaves messages in her web to save him. A profound meditation on friendship, mortality, and the cycles of life — told with warmth, humor, and perfect simplicity.",
        "reading_level": "early-intermediate",
        "age_range": "6-10",
        "subjects": ["literature", "nature", "friendship"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780061124952",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 99,
        "page_count": 184,
        "publication_year": 1952,
        "publisher": "Harper & Brothers",
    },
    {
        "title": "Beautiful Stories from Shakespeare",
        "author": "E. Nesbit",
        "description": "Shakespeare's greatest plays retold as vivid, accessible stories for young readers by the masterful children's author E. Nesbit.",
        "reading_level": "intermediate",
        "age_range": "8-14",
        "subjects": ["literature", "drama", "classics"],
        "time_period": "Renaissance",
        "region": "Europe",
        "isbn": "9781514684474",
        "language": "English",
        "popularity_score": 78,
        "page_count": 180,
        "publication_year": 1907,
        "publisher": "Various",
    },
    {
        "title": "This Country of Ours",
        "author": "H.E. Marshall",
        "description": "American history from the Norse discoveries through the early 20th century, told as a gripping narrative that brings the past alive.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["history", "American history"],
        "time_period": "Multiple periods",
        "region": "North America",
        "isbn": "9781599152622",
        "language": "English",
        "popularity_score": 85,
        "page_count": 480,
        "publication_year": 1917,
        "publisher": "Yesterday's Classics",
    },
    {
        "title": "Understood Betsy",
        "author": "Dorothy Canfield Fisher",
        "description": "An over-protected city girl discovers independence, confidence, and the joy of learning when she goes to live with Vermont relatives.",
        "reading_level": "early-intermediate",
        "age_range": "7-11",
        "subjects": ["literature", "character", "farm life"],
        "time_period": "Early 20th century",
        "region": "North America",
        "isbn": "9780805005806",
        "language": "English",
        "popularity_score": 88,
        "page_count": 224,
        "publication_year": 1917,
        "publisher": "Henry Holt",
    },
    {
        "title": "The Wind in the Willows",
        "author": "Kenneth Grahame",
        "description": "The eternal story of Mole, Ratty, Badger, and the irrepressible Mr. Toad — a masterpiece of English literature bursting with nature and friendship.",
        "reading_level": "intermediate",
        "age_range": "7-12",
        "subjects": ["literature", "nature", "friendship", "classics"],
        "time_period": "Edwardian era",
        "region": "Europe",
        "isbn": "9780143039099",
        "language": "English",
        "popularity_score": 93,
        "page_count": 272,
        "publication_year": 1908,
        "publisher": "Methuen",
    },
    {
        "title": "Pilgrim's Progress",
        "author": "John Bunyan (retold by Mary Godolphin)",
        "description": "The allegorical masterpiece retold in simple one-syllable words, making this profound journey accessible to even young readers.",
        "reading_level": "early",
        "age_range": "6-10",
        "subjects": ["literature", "religion", "classics", "allegory"],
        "time_period": "17th century",
        "region": "Europe",
        "isbn": "9781882514502",
        "language": "English",
        "popularity_score": 76,
        "page_count": 128,
        "publication_year": 1884,
        "publisher": "Yesterday's Classics",
    },
    {
        "title": "Blueberries for Sal",
        "author": "Robert McCloskey",
        "description": "Little Sal and her mother pick blueberries on one side of Blueberry Hill while a bear and her cub eat on the other — with a delightful mix-up.",
        "reading_level": "early",
        "age_range": "3-7",
        "subjects": ["nature", "family", "picture book"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780140501698",
        "language": "English",
        "awards": ["Caldecott Honor"],
        "popularity_score": 90,
        "page_count": 56,
        "publication_year": 1948,
        "publisher": "Viking Press",
    },
    {
        "title": "The Burgess Bird Book for Children",
        "author": "Thornton W. Burgess",
        "description": "Through delightful stories of Peter Rabbit and his woodland friends, children learn to identify and appreciate dozens of North American birds.",
        "reading_level": "read-aloud",
        "age_range": "5-10",
        "subjects": ["nature", "science", "birds", "wildlife"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780486428406",
        "language": "English",
        "popularity_score": 82,
        "page_count": 336,
        "publication_year": 1919,
        "publisher": "Dover Publications",
    },
    {
        "title": "Little House in the Big Woods",
        "author": "Laura Ingalls Wilder",
        "description": "The first book in the beloved Little House series, bringing pioneer life in 1870s Wisconsin alive through the eyes of young Laura.",
        "reading_level": "early-intermediate",
        "age_range": "6-10",
        "subjects": ["history", "pioneer life", "family", "American frontier"],
        "time_period": "19th century",
        "region": "North America",
        "isbn": "9780064400015",
        "language": "English",
        "series": "Little House",
        "awards": ["Newbery Honor"],
        "popularity_score": 97,
        "page_count": 238,
        "publication_year": 1932,
        "publisher": "Harper & Brothers",
    },
    {
        "title": "Anne of Green Gables",
        "author": "L.M. Montgomery",
        "description": "Red-haired, imaginative orphan Anne Shirley transforms the lives of everyone in Avonlea with her irrepressible spirit and love of beauty.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["literature", "character", "family", "classics"],
        "time_period": "Late 19th century",
        "region": "Canada",
        "isbn": "9780141321592",
        "language": "English",
        "series": "Anne of Green Gables",
        "popularity_score": 96,
        "page_count": 320,
        "publication_year": 1908,
        "publisher": "L.C. Page & Co.",
    },
    {
        "title": "The Secret Garden",
        "author": "Frances Hodgson Burnett",
        "description": "A spoiled, neglected girl discovers a hidden garden and, through nurturing it back to life, heals herself and those around her.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["literature", "nature", "character", "classics"],
        "time_period": "Edwardian era",
        "region": "Europe",
        "isbn": "9780064401883",
        "language": "English",
        "popularity_score": 94,
        "page_count": 288,
        "publication_year": 1911,
        "publisher": "Frederick A. Stokes",
    },
    {
        "title": "Treasure Island",
        "author": "Robert Louis Stevenson",
        "description": "Young Jim Hawkins finds a treasure map and sails into the adventure of a lifetime with the cunning pirate Long John Silver.",
        "reading_level": "advanced",
        "age_range": "10-15",
        "subjects": ["literature", "adventure", "classics"],
        "time_period": "18th century",
        "region": "Europe",
        "isbn": "9780141321004",
        "language": "English",
        "popularity_score": 91,
        "page_count": 311,
        "publication_year": 1883,
        "publisher": "Cassell and Company",
    },
    {
        "title": "The Handbook of Nature Study",
        "author": "Anna Botsford Comstock",
        "description": "The indispensable guide for nature study — covering birds, insects, plants, rocks, and weather with detailed lessons and gorgeous illustrations.",
        "reading_level": "teacher-reference",
        "age_range": "6-adult",
        "subjects": ["nature", "science", "teacher resource"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780801493843",
        "language": "English",
        "popularity_score": 88,
        "page_count": 887,
        "publication_year": 1911,
        "publisher": "Comstock Publishing",
    },
    {
        "title": "A Child's Geography of the World",
        "author": "V.M. Hillyer",
        "description": "A conversational tour of the entire world that makes geography irresistibly fascinating for young minds.",
        "reading_level": "early-intermediate",
        "age_range": "6-10",
        "subjects": ["geography", "world cultures"],
        "time_period": "20th century",
        "region": "World",
        "isbn": "9781882514199",
        "language": "English",
        "series": "Calvert School",
        "popularity_score": 80,
        "page_count": 318,
        "publication_year": 1929,
        "publisher": "Yesterday's Classics",
    },
    {
        "title": "A Child's History of the World",
        "author": "V.M. Hillyer",
        "description": "World history told as one great story — from cavemen to the modern age — in a warm, conversational voice that captivates young listeners.",
        "reading_level": "read-aloud",
        "age_range": "6-10",
        "subjects": ["history", "world history"],
        "time_period": "Multiple periods",
        "region": "World",
        "isbn": "9781882514205",
        "language": "English",
        "series": "Calvert School",
        "popularity_score": 82,
        "page_count": 382,
        "publication_year": 1924,
        "publisher": "Yesterday's Classics",
    },
    {
        "title": "The Door in the Wall",
        "author": "Marguerite de Angeli",
        "description": "A crippled boy in medieval England discovers that courage and determination can open doors that seem forever closed.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["history", "medieval", "character", "disability"],
        "time_period": "Medieval",
        "region": "Europe",
        "isbn": "9780440402831",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 84,
        "page_count": 128,
        "publication_year": 1949,
        "publisher": "Doubleday",
    },
    {
        "title": "Island of the Blue Dolphins",
        "author": "Scott O'Dell",
        "description": "Based on a true story: a Native American girl survives alone for eighteen years on an island off the California coast.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["history", "survival", "nature", "Native American"],
        "time_period": "19th century",
        "region": "North America",
        "isbn": "9780547328614",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 90,
        "page_count": 192,
        "publication_year": 1960,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Number the Stars",
        "author": "Lois Lowry",
        "description": "Ten-year-old Annemarie must find the courage to help shelter her Jewish friend from the Nazis in occupied Copenhagen.",
        "reading_level": "intermediate",
        "age_range": "9-12",
        "subjects": ["history", "World War II", "courage", "friendship"],
        "time_period": "World War II",
        "region": "Europe",
        "isbn": "9780547577098",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 89,
        "page_count": 160,
        "publication_year": 1989,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Heidi",
        "author": "Johanna Spyri",
        "description": "A joyful orphan girl brought to live with her gruff grandfather in the Swiss Alps transforms everyone she meets with her innocent goodness.",
        "reading_level": "intermediate",
        "age_range": "7-12",
        "subjects": ["literature", "nature", "character", "classics"],
        "time_period": "19th century",
        "region": "Europe",
        "isbn": "9780140620986",
        "language": "English",
        "popularity_score": 91,
        "page_count": 352,
        "publication_year": 1881,
        "publisher": "Various",
    },
    {
        "title": "The Moffats",
        "author": "Eleanor Estes",
        "description": "Warm, funny, and utterly real stories of the four Moffat children growing up in a small Connecticut town during World War I.",
        "reading_level": "early-intermediate",
        "age_range": "7-11",
        "subjects": ["literature", "family", "humor"],
        "time_period": "World War I era",
        "region": "North America",
        "isbn": "9780152025359",
        "language": "English",
        "series": "The Moffats",
        "popularity_score": 79,
        "page_count": 304,
        "publication_year": 1941,
        "publisher": "Harcourt",
    },
    {
        "title": "Misty of Chincoteague",
        "author": "Marguerite Henry",
        "description": "Two children dream of owning a wild pony from the island of Chincoteague — based on the real annual pony penning tradition.",
        "reading_level": "early-intermediate",
        "age_range": "7-11",
        "subjects": ["nature", "animals", "adventure"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9781416927839",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 87,
        "page_count": 176,
        "publication_year": 1947,
        "publisher": "Rand McNally",
    },
    {
        "title": "Amos Fortune, Free Man",
        "author": "Elizabeth Yates",
        "description": "The true story of an African prince who was captured, enslaved, and eventually bought his freedom and the freedom of others in colonial New England.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["history", "biography", "slavery", "freedom", "character"],
        "time_period": "18th century",
        "region": "North America",
        "isbn": "9780140341584",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 83,
        "page_count": 192,
        "publication_year": 1950,
        "publisher": "Dutton",
    },
    {
        "title": "Rascal",
        "author": "Sterling North",
        "description": "A boy's year-long friendship with a mischievous baby raccoon in rural Wisconsin — one of the most charming nature memoirs ever written.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["nature", "animals", "memoir", "friendship"],
        "time_period": "World War I era",
        "region": "North America",
        "isbn": "9780140341454",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 81,
        "page_count": 189,
        "publication_year": 1963,
        "publisher": "Dutton",
    },
    {
        "title": "The Trumpeter of Krakow",
        "author": "Eric P. Kelly",
        "description": "A young boy and his family guard a priceless jewel in 15th-century Krakow while the boy takes up the ancient duty of the trumpeter.",
        "reading_level": "advanced",
        "age_range": "10-14",
        "subjects": ["history", "medieval", "adventure", "Poland"],
        "time_period": "15th century",
        "region": "Europe",
        "isbn": "9780689715716",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 75,
        "page_count": 208,
        "publication_year": 1928,
        "publisher": "Macmillan",
    },
    {
        "title": "D'Aulaires' Book of Greek Myths",
        "author": "Ingri and Edgar Parin d'Aulaire",
        "description": "The definitive introduction to Greek mythology for children, with magnificent lithograph illustrations and masterful retellings.",
        "reading_level": "early-intermediate",
        "age_range": "6-12",
        "subjects": ["mythology", "ancient Greece", "classics"],
        "time_period": "Ancient",
        "region": "Europe",
        "isbn": "9780440406945",
        "language": "English",
        "popularity_score": 94,
        "page_count": 192,
        "publication_year": 1962,
        "publisher": "Doubleday",
    },
    {
        "title": "The Story of Mankind",
        "author": "Hendrik Willem van Loon",
        "description": "The first Newbery Medal winner: a sweeping narrative of human civilization from prehistoric times to the modern era.",
        "reading_level": "advanced",
        "age_range": "10-15",
        "subjects": ["history", "world history", "civilization"],
        "time_period": "Multiple periods",
        "region": "World",
        "isbn": "9780871401540",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 77,
        "page_count": 480,
        "publication_year": 1921,
        "publisher": "Boni & Liveright",
    },
    {
        "title": "Pagoo",
        "author": "Holling C. Holling",
        "description": "The life cycle of a hermit crab explored through stunning illustrations and a narrative that makes marine biology unforgettable.",
        "reading_level": "early-intermediate",
        "age_range": "6-10",
        "subjects": ["nature", "science", "marine biology"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780395539644",
        "language": "English",
        "popularity_score": 80,
        "page_count": 88,
        "publication_year": 1957,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Tree in the Trail",
        "author": "Holling C. Holling",
        "description": "A cottonwood tree along the Santa Fe Trail witnesses two hundred years of American history from Native Americans to westward expansion.",
        "reading_level": "early-intermediate",
        "age_range": "7-12",
        "subjects": ["history", "nature", "American frontier", "geography"],
        "time_period": "Multiple periods",
        "region": "North America",
        "isbn": "9780395546826",
        "language": "English",
        "popularity_score": 81,
        "page_count": 64,
        "publication_year": 1942,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Minn of the Mississippi",
        "author": "Holling C. Holling",
        "description": "A snapping turtle's journey down the Mississippi River becomes a rich lesson in geography, natural history, and American culture.",
        "reading_level": "early-intermediate",
        "age_range": "7-12",
        "subjects": ["geography", "nature", "science"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780395273999",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 82,
        "page_count": 88,
        "publication_year": 1951,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Seabird",
        "author": "Holling C. Holling",
        "description": "A carved ivory gull accompanies four generations of seafarers from whaling ships to modern aircraft, tracing the evolution of transportation.",
        "reading_level": "early-intermediate",
        "age_range": "7-12",
        "subjects": ["history", "adventure", "maritime", "transportation"],
        "time_period": "Multiple periods",
        "region": "North America",
        "isbn": "9780395266816",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 79,
        "page_count": 64,
        "publication_year": 1948,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Robin Hood",
        "author": "Howard Pyle",
        "description": "The classic retelling of Robin Hood and his merry men in Sherwood Forest — swashbuckling adventure paired with Pyle's magnificent illustrations.",
        "reading_level": "advanced",
        "age_range": "10-15",
        "subjects": ["literature", "adventure", "medieval", "classics"],
        "time_period": "Medieval",
        "region": "Europe",
        "isbn": "9780486220437",
        "language": "English",
        "popularity_score": 86,
        "page_count": 312,
        "publication_year": 1883,
        "publisher": "Charles Scribner's Sons",
    },
    {
        "title": "King of the Wind",
        "author": "Marguerite Henry",
        "description": "The true story of the Godolphin Arabian, one of the three founding sires of the Thoroughbred breed, and his devoted mute stable boy.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["history", "animals", "biography"],
        "time_period": "18th century",
        "region": "Africa",
        "isbn": "9781416927860",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 83,
        "page_count": 176,
        "publication_year": 1948,
        "publisher": "Rand McNally",
    },
    {
        "title": "The Twenty-One Balloons",
        "author": "William Pène du Bois",
        "description": "Professor Sherman's hot-air balloon adventure leads him to the secret, fantastical civilization on the volcanic island of Krakatoa.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["adventure", "science", "humor", "invention"],
        "time_period": "19th century",
        "region": "Asia",
        "isbn": "9780140320978",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 82,
        "page_count": 180,
        "publication_year": 1947,
        "publisher": "Viking Press",
    },
    {
        "title": "Caddie Woodlawn",
        "author": "Carol Ryrie Brink",
        "description": "Based on her grandmother's stories, the adventures of a spirited tomboy growing up on the Wisconsin frontier in the 1860s.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["history", "pioneer life", "family", "American frontier"],
        "time_period": "19th century",
        "region": "North America",
        "isbn": "9781416940289",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 86,
        "page_count": 275,
        "publication_year": 1935,
        "publisher": "Macmillan",
    },
    {
        "title": "The Wheel on the School",
        "author": "Meindert DeJong",
        "description": "Six schoolchildren in a Dutch fishing village work together to bring the storks back to nest on their school roof.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["literature", "nature", "community", "Netherlands"],
        "time_period": "20th century",
        "region": "Europe",
        "isbn": "9780064402101",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 78,
        "page_count": 298,
        "publication_year": 1954,
        "publisher": "Harper",
    },
    {
        "title": "The Matchlock Gun",
        "author": "Walter D. Edmonds",
        "description": "A ten-year-old boy must defend his mother and baby sister with an ancient Spanish matchlock gun during a raid on their colonial home.",
        "reading_level": "early-intermediate",
        "age_range": "7-11",
        "subjects": ["history", "colonial America", "courage"],
        "time_period": "Colonial era",
        "region": "North America",
        "isbn": "9780698116801",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 74,
        "page_count": 64,
        "publication_year": 1941,
        "publisher": "Dodd, Mead",
    },
    {
        "title": "Watership Down",
        "author": "Richard Adams",
        "description": "A band of rabbits flee their doomed warren and embark on an epic journey to find a new home — a sweeping tale of courage, leadership, and myth.",
        "reading_level": "advanced",
        "age_range": "12-adult",
        "subjects": ["literature", "adventure", "nature", "leadership", "classics"],
        "time_period": "20th century",
        "region": "Europe",
        "isbn": "9780743277709",
        "language": "English",
        "awards": ["Carnegie Medal"],
        "popularity_score": 92,
        "page_count": 478,
        "publication_year": 1972,
        "publisher": "Rex Collings",
    },
    {
        "title": "The Hobbit",
        "author": "J.R.R. Tolkien",
        "description": "Bilbo Baggins leaves his comfortable hobbit-hole and joins thirteen dwarves on a quest to reclaim their mountain home from a dragon.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["literature", "fantasy", "adventure", "classics"],
        "time_period": "Fantasy",
        "region": "Fantasy World",
        "isbn": "9780547928227",
        "language": "English",
        "popularity_score": 97,
        "page_count": 310,
        "publication_year": 1937,
        "publisher": "George Allen & Unwin",
    },
    {
        "title": "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        "author": "C.S. Lewis",
        "description": "Four children enter a magical world through a wardrobe and join the great lion Aslan in the battle against the White Witch's eternal winter.",
        "reading_level": "intermediate",
        "age_range": "8-13",
        "subjects": ["literature", "fantasy", "allegory", "classics"],
        "time_period": "Fantasy",
        "region": "Fantasy World",
        "isbn": "9780064471046",
        "language": "English",
        "series": "Chronicles of Narnia",
        "popularity_score": 98,
        "page_count": 208,
        "publication_year": 1950,
        "publisher": "Geoffrey Bles",
    },
    {
        "title": "A Wrinkle in Time",
        "author": "Madeleine L'Engle",
        "description": "Meg Murry, her brother Charles Wallace, and friend Calvin travel through a wrinkle in time to rescue her father from a dark force.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["literature", "science fiction", "family", "courage"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780312367541",
        "language": "English",
        "awards": ["Newbery Medal"],
        "series": "Time Quintet",
        "popularity_score": 93,
        "page_count": 256,
        "publication_year": 1962,
        "publisher": "Farrar, Straus and Giroux",
    },
    {
        "title": "Johnny Tremain",
        "author": "Esther Forbes",
        "description": "A young silversmith's apprentice in Boston becomes a key player in the events leading up to the American Revolution.",
        "reading_level": "intermediate",
        "age_range": "10-14",
        "subjects": ["history", "American Revolution", "coming of age"],
        "time_period": "18th century",
        "region": "North America",
        "isbn": "9780547614328",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 87,
        "page_count": 256,
        "publication_year": 1943,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Little Britches: Father and I Were Ranchers",
        "author": "Ralph Moody",
        "description": "A boy's adventures growing up on a Colorado ranch in the early 1900s — hardship, humor, and the making of character.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["memoir", "ranch life", "character", "American West"],
        "time_period": "Early 20th century",
        "region": "North America",
        "isbn": "9780803281783",
        "language": "English",
        "series": "Little Britches",
        "popularity_score": 88,
        "page_count": 260,
        "publication_year": 1950,
        "publisher": "W.W. Norton",
    },
    {
        "title": "The Good Master",
        "author": "Kate Seredy",
        "description": "A spirited city girl is sent to live on her uncle's ranch on the Hungarian plains, where she discovers a world of horses, folk traditions, and family.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["literature", "culture", "Hungary", "family", "horses"],
        "time_period": "Early 20th century",
        "region": "Europe",
        "isbn": "9780140301335",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 77,
        "page_count": 210,
        "publication_year": 1935,
        "publisher": "Viking Press",
    },
    {
        "title": "Where the Red Fern Grows",
        "author": "Wilson Rawls",
        "description": "A boy in the Ozarks saves for two coonhound pups and together they become the finest hunting team in the valley — a story of love, loyalty, and loss.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["literature", "nature", "animals", "coming of age"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780440412670",
        "language": "English",
        "popularity_score": 93,
        "page_count": 249,
        "publication_year": 1961,
        "publisher": "Doubleday",
    },
    {
        "title": "The Bronze Bow",
        "author": "Elizabeth George Speare",
        "description": "A young Jewish rebel in first-century Palestine is consumed by hatred of the Romans until he encounters Jesus of Nazareth.",
        "reading_level": "advanced",
        "age_range": "10-14",
        "subjects": ["history", "biblical era", "character", "religion"],
        "time_period": "Ancient",
        "region": "Middle East",
        "isbn": "9780395137192",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 82,
        "page_count": 254,
        "publication_year": 1961,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "The Witch of Blackbird Pond",
        "author": "Elizabeth George Speare",
        "description": "Kit Tyler, raised in tropical Barbados, struggles to fit into Puritan Connecticut — and her friendship with a Quaker woman leads to accusations of witchcraft.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["history", "colonial America", "character", "religious freedom"],
        "time_period": "Colonial era",
        "region": "North America",
        "isbn": "9780547550299",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 89,
        "page_count": 249,
        "publication_year": 1958,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Make Way for Ducklings",
        "author": "Robert McCloskey",
        "description": "Mr. and Mrs. Mallard search for the perfect place to raise their family in Boston — a joyful picture book classic.",
        "reading_level": "early",
        "age_range": "3-7",
        "subjects": ["nature", "picture book", "family"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780140564341",
        "language": "English",
        "awards": ["Caldecott Medal"],
        "popularity_score": 91,
        "page_count": 68,
        "publication_year": 1941,
        "publisher": "Viking Press",
    },
    {
        "title": "Ox-Cart Man",
        "author": "Donald Hall",
        "description": "The cycle of a New England farming family through the seasons — planting, harvesting, selling, and beginning again. Illustrated by Barbara Cooney.",
        "reading_level": "early",
        "age_range": "4-8",
        "subjects": ["history", "farm life", "picture book", "seasons"],
        "time_period": "19th century",
        "region": "North America",
        "isbn": "9780140504415",
        "language": "English",
        "awards": ["Caldecott Medal"],
        "popularity_score": 84,
        "page_count": 40,
        "publication_year": 1979,
        "publisher": "Viking Press",
    },
    # === SCIENCE & MATH ===
    {
        "title": "The Story of Science: Aristotle Leads the Way",
        "author": "Joy Hakim",
        "description": "The epic story of how humans learned to think scientifically — from ancient Mesopotamia through the Greek golden age.",
        "long_description": "Joy Hakim does for science what the best historical novelists do for history: she makes it a story you can't put down. From Thales to Aristotle, this book traces the birth of scientific thinking with clarity, wit, and a gift for making abstract ideas tangible for young minds.",
        "reading_level": "intermediate",
        "age_range": "10-15",
        "subjects": ["science", "history of science", "philosophy"],
        "time_period": "Ancient",
        "region": "World",
        "isbn": "9781588341600",
        "language": "English",
        "series": "The Story of Science",
        "popularity_score": 85,
        "page_count": 282,
        "publication_year": 2004,
        "publisher": "Smithsonian Books",
    },
    {
        "title": "Archimedes and the Door of Science",
        "author": "Jeanne Bendick",
        "description": "The life and discoveries of Archimedes — levers, pulleys, pi, and the famous bathtub 'Eureka!' — told with charm and clarity.",
        "reading_level": "early-intermediate",
        "age_range": "8-12",
        "subjects": ["science", "biography", "mathematics", "ancient Greece"],
        "time_period": "Ancient",
        "region": "Europe",
        "isbn": "9781883937126",
        "language": "English",
        "popularity_score": 80,
        "page_count": 143,
        "publication_year": 1962,
        "publisher": "Bethlehem Books",
    },
    {
        "title": "The Mystery of the Periodic Table",
        "author": "Benjamin D. Wiker",
        "description": "The thrilling detective story of how scientists discovered the elements — from ancient alchemy to Mendeleev's breakthrough.",
        "reading_level": "intermediate",
        "age_range": "10-15",
        "subjects": ["science", "chemistry", "history of science"],
        "time_period": "Multiple periods",
        "region": "World",
        "isbn": "9781883937713",
        "language": "English",
        "popularity_score": 78,
        "page_count": 168,
        "publication_year": 2003,
        "publisher": "Bethlehem Books",
    },
    {
        "title": "Discovering Great Artists",
        "author": "MaryAnn F. Kohl",
        "description": "Hands-on art activities inspired by the great masters — from Da Vinci to Pollock — making art history a living, creative experience.",
        "reading_level": "teacher-reference",
        "age_range": "4-12",
        "subjects": ["art", "art history", "hands-on activities"],
        "time_period": "Multiple periods",
        "region": "World",
        "isbn": "9780935607093",
        "language": "English",
        "popularity_score": 82,
        "page_count": 144,
        "publication_year": 1996,
        "publisher": "Bright Ring Publishing",
    },
    {
        "title": "Mathematician's Delight",
        "author": "W.W. Sawyer",
        "description": "A masterful introduction to mathematical thinking that makes algebra, geometry, and calculus genuinely exciting and intuitive.",
        "reading_level": "advanced",
        "age_range": "12-adult",
        "subjects": ["mathematics", "logic"],
        "time_period": "20th century",
        "region": "World",
        "isbn": "9780486462400",
        "language": "English",
        "popularity_score": 72,
        "page_count": 238,
        "publication_year": 1943,
        "publisher": "Dover Publications",
    },
    {
        "title": "The Life of Fred: Fractions",
        "author": "Stanley F. Schmidt",
        "description": "Five-year-old Fred teaches fractions through hilarious misadventures at KITTENS University — math has never been this fun.",
        "reading_level": "early-intermediate",
        "age_range": "7-11",
        "subjects": ["mathematics", "humor"],
        "time_period": "Contemporary",
        "region": "North America",
        "isbn": "9780979107214",
        "language": "English",
        "series": "Life of Fred",
        "popularity_score": 88,
        "page_count": 192,
        "publication_year": 2007,
        "publisher": "Polka Dot Publishing",
    },
    {
        "title": "Fabre's Book of Insects",
        "author": "Jean-Henri Fabre",
        "description": "The legendary entomologist's observations retold for young readers — each insect portrait so vivid you can almost hear the buzzing.",
        "reading_level": "intermediate",
        "age_range": "8-13",
        "subjects": ["science", "nature", "insects", "biology"],
        "time_period": "19th century",
        "region": "Europe",
        "isbn": "9780486401522",
        "language": "English",
        "popularity_score": 76,
        "page_count": 200,
        "publication_year": 1921,
        "publisher": "Dover Publications",
    },
    # === POETRY ===
    {
        "title": "A Child's Garden of Verses",
        "author": "Robert Louis Stevenson",
        "description": "The beloved collection of childhood poems — 'The Swing,' 'My Shadow,' 'The Land of Counterpane' — pure magic for young ears.",
        "long_description": "Stevenson wrote these poems while bedridden with illness, remembering his own childhood with photographic tenderness. These verses capture the inner world of a child with perfect rhythm, vivid imagery, and a gentleness that has enchanted families for over a century.",
        "reading_level": "early",
        "age_range": "3-8",
        "subjects": ["poetry", "literature", "classics"],
        "time_period": "Victorian era",
        "region": "Europe",
        "isbn": "9780689823824",
        "language": "English",
        "popularity_score": 90,
        "page_count": 112,
        "publication_year": 1885,
        "publisher": "Various",
    },
    {
        "title": "Favorite Poems Old and New",
        "author": "Helen Ferris (editor)",
        "description": "The definitive poetry anthology for families — over 700 poems organized by theme, from silly rhymes to Shakespeare.",
        "reading_level": "read-aloud",
        "age_range": "4-14",
        "subjects": ["poetry", "literature", "anthology"],
        "time_period": "Multiple periods",
        "region": "World",
        "isbn": "9780385076968",
        "language": "English",
        "popularity_score": 86,
        "page_count": 598,
        "publication_year": 1957,
        "publisher": "Doubleday",
    },
    {
        "title": "Hailstones and Halibut Bones",
        "author": "Mary O'Neill",
        "description": "Twelve poems about colors that teach children to see the world in vivid, sensory detail — 'What is Gold?' 'What is Purple?'",
        "reading_level": "early",
        "age_range": "4-9",
        "subjects": ["poetry", "art", "colors", "picture book"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780385410786",
        "language": "English",
        "popularity_score": 79,
        "page_count": 64,
        "publication_year": 1961,
        "publisher": "Doubleday",
    },
    # === BIOGRAPHY ===
    {
        "title": "George Washington's World",
        "author": "Genevieve Foster",
        "description": "What was happening around the world during George Washington's lifetime — a panoramic view of the 18th century.",
        "long_description": "Foster pioneered the 'horizontal history' approach: instead of studying one country's timeline, she shows what was happening everywhere at the same time. While Washington fought for independence, Mozart composed, Captain Cook explored the Pacific, and Napoleon rose to power. History becomes a living, interconnected tapestry.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["history", "biography", "world history"],
        "time_period": "18th century",
        "region": "World",
        "isbn": "9780964380691",
        "language": "English",
        "series": "Foster's World Books",
        "popularity_score": 84,
        "page_count": 350,
        "publication_year": 1941,
        "publisher": "Beautiful Feet Books",
    },
    {
        "title": "Abraham Lincoln's World",
        "author": "Genevieve Foster",
        "description": "The world during Lincoln's lifetime — from Beethoven's symphonies to the opening of Japan to Darwin's voyage on the Beagle.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["history", "biography", "world history"],
        "time_period": "19th century",
        "region": "World",
        "isbn": "9780964380615",
        "language": "English",
        "series": "Foster's World Books",
        "awards": ["Newbery Honor"],
        "popularity_score": 82,
        "page_count": 348,
        "publication_year": 1944,
        "publisher": "Beautiful Feet Books",
    },
    {
        "title": "The Wright Brothers: How They Invented the Airplane",
        "author": "Russell Freedman",
        "description": "The true story of Orville and Wilbur's journey to flight, illustrated with their own stunning photographs.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["biography", "science", "aviation", "invention"],
        "time_period": "Early 20th century",
        "region": "North America",
        "isbn": "9780823412976",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 81,
        "page_count": 129,
        "publication_year": 1991,
        "publisher": "Holiday House",
    },
    {
        "title": "Men of Iron",
        "author": "Howard Pyle",
        "description": "A young squire trains for knighthood in 15th-century England — thrilling combat, medieval honor, and Pyle's magnificent illustrations.",
        "reading_level": "advanced",
        "age_range": "10-15",
        "subjects": ["history", "medieval", "adventure", "chivalry"],
        "time_period": "15th century",
        "region": "Europe",
        "isbn": "9780486253411",
        "language": "English",
        "popularity_score": 77,
        "page_count": 240,
        "publication_year": 1891,
        "publisher": "Dover Publications",
    },
    {
        "title": "Invincible Louisa",
        "author": "Cornelia Meigs",
        "description": "The biography of Louisa May Alcott — her passionate family, her struggles as a writer, and the creation of Little Women.",
        "reading_level": "intermediate",
        "age_range": "10-14",
        "subjects": ["biography", "literature", "women's history"],
        "time_period": "19th century",
        "region": "North America",
        "isbn": "9780316565943",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 74,
        "page_count": 260,
        "publication_year": 1933,
        "publisher": "Little, Brown",
    },
    # === WORLD CULTURES & LITERATURE ===
    {
        "title": "The Jungle Book",
        "author": "Rudyard Kipling",
        "description": "Mowgli, raised by wolves in the Indian jungle, learns the law of the jungle from Baloo, Bagheera, and Kaa.",
        "reading_level": "intermediate",
        "age_range": "8-13",
        "subjects": ["literature", "nature", "India", "adventure", "classics"],
        "time_period": "19th century",
        "region": "Asia",
        "isbn": "9780141325293",
        "language": "English",
        "popularity_score": 89,
        "page_count": 277,
        "publication_year": 1894,
        "publisher": "Macmillan",
    },
    {
        "title": "The Story of Doctor Dolittle",
        "author": "Hugh Lofting",
        "description": "A doctor who can talk to animals sets off on extraordinary adventures across the globe.",
        "reading_level": "early-intermediate",
        "age_range": "6-10",
        "subjects": ["literature", "animals", "adventure", "humor"],
        "time_period": "Victorian era",
        "region": "World",
        "isbn": "9780440483076",
        "language": "English",
        "series": "Doctor Dolittle",
        "popularity_score": 82,
        "page_count": 176,
        "publication_year": 1920,
        "publisher": "Frederick A. Stokes",
    },
    {
        "title": "The Railway Children",
        "author": "E. Nesbit",
        "description": "Three children move to the countryside near a railway line and have adventures that test their courage and kindness.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["literature", "family", "British literature", "classics"],
        "time_period": "Edwardian era",
        "region": "Europe",
        "isbn": "9780141321608",
        "language": "English",
        "popularity_score": 80,
        "page_count": 256,
        "publication_year": 1906,
        "publisher": "Wells Gardner",
    },
    {
        "title": "Black Beauty",
        "author": "Anna Sewell",
        "description": "The autobiography of a horse — from gentle country life to harsh city labor — a timeless story of compassion and animal welfare.",
        "reading_level": "intermediate",
        "age_range": "8-13",
        "subjects": ["literature", "animals", "character", "classics"],
        "time_period": "Victorian era",
        "region": "Europe",
        "isbn": "9780141321035",
        "language": "English",
        "popularity_score": 87,
        "page_count": 256,
        "publication_year": 1877,
        "publisher": "Jarrold and Sons",
    },
    {
        "title": "Hans Brinker, or The Silver Skates",
        "author": "Mary Mapes Dodge",
        "description": "A Dutch boy dreams of winning the great skating race while trying to find a doctor to save his injured father.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["literature", "Netherlands", "culture", "family"],
        "time_period": "19th century",
        "region": "Europe",
        "isbn": "9780064401326",
        "language": "English",
        "popularity_score": 76,
        "page_count": 336,
        "publication_year": 1865,
        "publisher": "Various",
    },
    {
        "title": "Tales from Shakespeare",
        "author": "Charles and Mary Lamb",
        "description": "Twenty of Shakespeare's plays retold as elegant prose stories — the gateway to the Bard for young readers.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["literature", "drama", "Shakespeare", "classics"],
        "time_period": "Renaissance",
        "region": "Europe",
        "isbn": "9780141321684",
        "language": "English",
        "popularity_score": 80,
        "page_count": 336,
        "publication_year": 1807,
        "publisher": "Various",
    },
    # === MORE HISTORY ===
    {
        "title": "Augustus Caesar's World",
        "author": "Genevieve Foster",
        "description": "The world of 44 BC to 14 AD — from the fall of the Roman Republic to the birth of Christianity, told as living history.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["history", "ancient Rome", "world history", "biography"],
        "time_period": "Ancient",
        "region": "World",
        "isbn": "9780964380639",
        "language": "English",
        "series": "Foster's World Books",
        "popularity_score": 80,
        "page_count": 330,
        "publication_year": 1947,
        "publisher": "Beautiful Feet Books",
    },
    {
        "title": "The Story of the World, Volume 2: The Middle Ages",
        "author": "Susan Wise Bauer",
        "description": "History from the fall of Rome through the Renaissance — told as a captivating narrative for young listeners.",
        "reading_level": "read-aloud",
        "age_range": "5-10",
        "subjects": ["history", "medieval", "world history"],
        "time_period": "Medieval",
        "region": "World",
        "isbn": "9781933339092",
        "language": "English",
        "series": "Story of the World",
        "popularity_score": 96,
        "page_count": 372,
        "publication_year": 2007,
        "publisher": "Peace Hill Press",
    },
    {
        "title": "The Story of the World, Volume 3: Early Modern Times",
        "author": "Susan Wise Bauer",
        "description": "From Elizabeth I to the dawn of the Industrial Revolution — world history told as a story for young minds.",
        "reading_level": "read-aloud",
        "age_range": "5-10",
        "subjects": ["history", "early modern", "world history"],
        "time_period": "Early Modern",
        "region": "World",
        "isbn": "9781933339108",
        "language": "English",
        "series": "Story of the World",
        "popularity_score": 94,
        "page_count": 400,
        "publication_year": 2004,
        "publisher": "Peace Hill Press",
    },
    {
        "title": "The Story of the World, Volume 4: The Modern Age",
        "author": "Susan Wise Bauer",
        "description": "From the age of revolution through the modern world — wars, inventions, civil rights, and the shaping of today.",
        "reading_level": "read-aloud",
        "age_range": "5-10",
        "subjects": ["history", "modern history", "world history"],
        "time_period": "Modern",
        "region": "World",
        "isbn": "9781933339115",
        "language": "English",
        "series": "Story of the World",
        "popularity_score": 93,
        "page_count": 468,
        "publication_year": 2005,
        "publisher": "Peace Hill Press",
    },
    {
        "title": "Otto of the Silver Hand",
        "author": "Howard Pyle",
        "description": "A gentle boy caught between warring medieval families learns that goodness can triumph over violence.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["history", "medieval", "character", "adventure"],
        "time_period": "Medieval",
        "region": "Europe",
        "isbn": "9780486217840",
        "language": "English",
        "popularity_score": 74,
        "page_count": 136,
        "publication_year": 1888,
        "publisher": "Dover Publications",
    },
    {
        "title": "Adam of the Road",
        "author": "Elizabeth Janet Gray",
        "description": "An eleven-year-old minstrel's son travels medieval England searching for his father and his stolen dog.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["history", "medieval", "adventure", "music"],
        "time_period": "13th century",
        "region": "Europe",
        "isbn": "9780140324648",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 77,
        "page_count": 320,
        "publication_year": 1942,
        "publisher": "Viking Press",
    },
    # === NATURE & SCIENCE (more) ===
    {
        "title": "Keeping a Nature Journal",
        "author": "Clare Walker Leslie",
        "description": "A practical, inspiring guide to observing and recording nature — the companion to outdoor exploration.",
        "reading_level": "teacher-reference",
        "age_range": "8-adult",
        "subjects": ["nature", "art", "science", "journaling"],
        "time_period": "Contemporary",
        "region": "North America",
        "isbn": "9781580174930",
        "language": "English",
        "popularity_score": 75,
        "page_count": 216,
        "publication_year": 2003,
        "publisher": "Storey Publishing",
    },
    {
        "title": "The Country Diary of an Edwardian Lady",
        "author": "Edith Holden",
        "description": "A naturalist's exquisite illustrated diary of the English countryside through the seasons — wildflowers, birds, and poetry.",
        "reading_level": "read-aloud",
        "age_range": "6-adult",
        "subjects": ["nature", "art", "seasons", "British countryside"],
        "time_period": "Edwardian era",
        "region": "Europe",
        "isbn": "9780030198717",
        "language": "English",
        "popularity_score": 80,
        "page_count": 192,
        "publication_year": 1977,
        "publisher": "Henry Holt",
    },
    {
        "title": "Owls in the Family",
        "author": "Farley Mowat",
        "description": "Two pet owls — Wol and Weeps — turn a Canadian boy's life upside down in this hilarious true story.",
        "reading_level": "early-intermediate",
        "age_range": "7-11",
        "subjects": ["nature", "animals", "humor", "memoir"],
        "time_period": "20th century",
        "region": "Canada",
        "isbn": "9780440413615",
        "language": "English",
        "popularity_score": 83,
        "page_count": 107,
        "publication_year": 1961,
        "publisher": "Little, Brown",
    },
    {
        "title": "My Side of the Mountain",
        "author": "Jean Craighead George",
        "description": "A boy runs away to the Catskill Mountains and survives alone in the wilderness with a falcon, a weasel, and his own ingenuity.",
        "reading_level": "intermediate",
        "age_range": "9-13",
        "subjects": ["nature", "survival", "adventure", "independence"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780142401118",
        "language": "English",
        "awards": ["Newbery Honor"],
        "popularity_score": 91,
        "page_count": 177,
        "publication_year": 1959,
        "publisher": "Dutton",
    },
    {
        "title": "The Ology Series: Dragonology",
        "author": "Dr. Ernest Drake",
        "description": "A richly illustrated 'field guide' to dragons — presented as a Victorian naturalist's journal with pull-out maps and specimens.",
        "reading_level": "early-intermediate",
        "age_range": "7-12",
        "subjects": ["fantasy", "nature", "art", "interactive"],
        "time_period": "Victorian era",
        "region": "World",
        "isbn": "9780763623296",
        "language": "English",
        "series": "Ology",
        "popularity_score": 84,
        "page_count": 30,
        "publication_year": 2003,
        "publisher": "Candlewick Press",
    },
    # === PICTURE BOOKS & EARLY READERS ===
    {
        "title": "The Story of Ferdinand",
        "author": "Munro Leaf",
        "description": "A young bull who would rather smell flowers than fight in the ring — a gentle, subversive classic about being true to yourself.",
        "reading_level": "early",
        "age_range": "3-7",
        "subjects": ["literature", "picture book", "character", "peace"],
        "time_period": "20th century",
        "region": "Europe",
        "isbn": "9780448421902",
        "language": "English",
        "popularity_score": 89,
        "page_count": 72,
        "publication_year": 1936,
        "publisher": "Viking Press",
    },
    {
        "title": "Mike Mulligan and His Steam Shovel",
        "author": "Virginia Lee Burton",
        "description": "Mike Mulligan and his beloved steam shovel Mary Anne prove they can dig as fast as modern machines — a celebration of determination.",
        "reading_level": "early",
        "age_range": "3-7",
        "subjects": ["literature", "picture book", "machines", "determination"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780395169612",
        "language": "English",
        "popularity_score": 87,
        "page_count": 48,
        "publication_year": 1939,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "The Little House",
        "author": "Virginia Lee Burton",
        "description": "A little house in the country watches the city grow up around her — a poignant story about progress, nature, and home.",
        "reading_level": "early",
        "age_range": "3-7",
        "subjects": ["literature", "picture book", "nature", "change"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780395259382",
        "language": "English",
        "awards": ["Caldecott Medal"],
        "popularity_score": 88,
        "page_count": 44,
        "publication_year": 1942,
        "publisher": "Houghton Mifflin",
    },
    {
        "title": "Caps for Sale",
        "author": "Esphyr Slobodkina",
        "description": "A peddler, a tree full of monkeys, and a stack of caps — one of the most satisfying read-alouds ever written.",
        "reading_level": "early",
        "age_range": "3-6",
        "subjects": ["literature", "picture book", "humor"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780064431439",
        "language": "English",
        "popularity_score": 86,
        "page_count": 48,
        "publication_year": 1940,
        "publisher": "Harper",
    },
    {
        "title": "Millions of Cats",
        "author": "Wanda Gág",
        "description": "An old man sets out to find one kitten and comes home with hundreds of cats, thousands of cats, millions and billions and trillions of cats.",
        "reading_level": "early",
        "age_range": "3-6",
        "subjects": ["literature", "picture book", "classics"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780698113633",
        "language": "English",
        "popularity_score": 84,
        "page_count": 32,
        "publication_year": 1928,
        "publisher": "Coward-McCann",
    },
    {
        "title": "Madeline",
        "author": "Ludwig Bemelmans",
        "description": "In an old house in Paris covered with vines lived twelve little girls in two straight lines — and the smallest one was Madeline.",
        "reading_level": "early",
        "age_range": "3-7",
        "subjects": ["literature", "picture book", "France", "courage"],
        "time_period": "20th century",
        "region": "Europe",
        "isbn": "9780140564396",
        "language": "English",
        "awards": ["Caldecott Honor"],
        "popularity_score": 92,
        "page_count": 56,
        "publication_year": 1939,
        "publisher": "Viking Press",
    },
    # === MORE LITERARY CLASSICS ===
    {
        "title": "Little Women",
        "author": "Louisa May Alcott",
        "description": "The four March sisters — Meg, Jo, Beth, and Amy — grow up during the Civil War, facing poverty, loss, and love with spirit and grace.",
        "long_description": "This is the book that launched a thousand readers. Alcott drew from her own family life to create characters so real they feel like friends. Jo March, fierce and literary; gentle Beth; vain Amy; responsible Meg — together they embody the joys and heartaches of growing up. It is as fresh today as the day it was published.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["literature", "family", "Civil War", "classics", "women's history"],
        "time_period": "19th century",
        "region": "North America",
        "isbn": "9780147514011",
        "language": "English",
        "popularity_score": 94,
        "page_count": 449,
        "publication_year": 1868,
        "publisher": "Various",
    },
    {
        "title": "Robinson Crusoe",
        "author": "Daniel Defoe",
        "description": "A man shipwrecked on a deserted island survives for 28 years through ingenuity, faith, and determination — the original survival story.",
        "reading_level": "advanced",
        "age_range": "10-15",
        "subjects": ["literature", "adventure", "survival", "classics"],
        "time_period": "18th century",
        "region": "World",
        "isbn": "9780141439822",
        "language": "English",
        "popularity_score": 85,
        "page_count": 320,
        "publication_year": 1719,
        "publisher": "Various",
    },
    {
        "title": "The Swiss Family Robinson",
        "author": "Johann David Wyss",
        "description": "A family shipwrecked on a tropical island builds an extraordinary life using wit, knowledge, and the bounty of nature.",
        "reading_level": "intermediate",
        "age_range": "9-14",
        "subjects": ["literature", "adventure", "survival", "family", "nature"],
        "time_period": "19th century",
        "region": "World",
        "isbn": "9780141325309",
        "language": "English",
        "popularity_score": 83,
        "page_count": 352,
        "publication_year": 1812,
        "publisher": "Various",
    },
    {
        "title": "Swallows and Amazons",
        "author": "Arthur Ransome",
        "description": "Four children sail, camp, and explore the English Lake District in a timeless adventure of childhood freedom and imagination.",
        "reading_level": "intermediate",
        "age_range": "8-13",
        "subjects": ["literature", "adventure", "sailing", "British literature"],
        "time_period": "20th century",
        "region": "Europe",
        "isbn": "9780099503910",
        "language": "English",
        "series": "Swallows and Amazons",
        "popularity_score": 82,
        "page_count": 352,
        "publication_year": 1930,
        "publisher": "Jonathan Cape",
    },
    {
        "title": "The Phantom Tollbooth",
        "author": "Norton Juster",
        "description": "Bored Milo drives through a mysterious tollbooth into the Kingdom of Wisdom — where words and numbers are alive, and learning is an adventure.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["literature", "fantasy", "humor", "wordplay", "mathematics"],
        "time_period": "20th century",
        "region": "Fantasy World",
        "isbn": "9780394820378",
        "language": "English",
        "popularity_score": 91,
        "page_count": 272,
        "publication_year": 1961,
        "publisher": "Random House",
    },
    {
        "title": "The Borrowers",
        "author": "Mary Norton",
        "description": "Tiny people living under the floorboards 'borrow' from the humans upstairs — until a boy discovers them and their world is threatened.",
        "reading_level": "early-intermediate",
        "age_range": "7-11",
        "subjects": ["literature", "fantasy", "adventure", "British literature"],
        "time_period": "20th century",
        "region": "Europe",
        "isbn": "9780152047375",
        "language": "English",
        "awards": ["Carnegie Medal"],
        "series": "The Borrowers",
        "popularity_score": 86,
        "page_count": 180,
        "publication_year": 1952,
        "publisher": "Harcourt",
    },
    {
        "title": "Mrs. Frisby and the Rats of NIMH",
        "author": "Robert C. O'Brien",
        "description": "A widowed mouse must move her family before the farmer's plow destroys their home — and turns to a colony of super-intelligent rats for help.",
        "reading_level": "intermediate",
        "age_range": "8-12",
        "subjects": ["literature", "fantasy", "science", "adventure"],
        "time_period": "20th century",
        "region": "North America",
        "isbn": "9780689710681",
        "language": "English",
        "awards": ["Newbery Medal"],
        "popularity_score": 89,
        "page_count": 233,
        "publication_year": 1971,
        "publisher": "Atheneum",
    },
    # === MUSIC & ART ===
    {
        "title": "Sebastian Bach, The Boy from Thuringia",
        "author": "Opal Wheeler",
        "description": "The childhood of Johann Sebastian Bach — how a musical genius grew up in a family of musicians in small-town Germany.",
        "reading_level": "early-intermediate",
        "age_range": "6-10",
        "subjects": ["biography", "music", "art"],
        "time_period": "17th century",
        "region": "Europe",
        "isbn": "9781893103139",
        "language": "English",
        "series": "Great Musicians Series",
        "popularity_score": 72,
        "page_count": 144,
        "publication_year": 1937,
        "publisher": "Zeezok Publishing",
    },
    {
        "title": "Beethoven Lives Upstairs",
        "author": "Barbara Nichol",
        "description": "A boy's hilarious and touching letters about the eccentric genius who moves into the apartment above — Ludwig van Beethoven.",
        "reading_level": "early-intermediate",
        "age_range": "6-10",
        "subjects": ["biography", "music", "humor"],
        "time_period": "19th century",
        "region": "Europe",
        "isbn": "9780531071182",
        "language": "English",
        "popularity_score": 81,
        "page_count": 52,
        "publication_year": 1993,
        "publisher": "Orchard Books",
    },
    {
        "title": "Getting to Know the World's Greatest Artists: Monet",
        "author": "Mike Venezia",
        "description": "An accessible, humorous introduction to Claude Monet and Impressionism — perfect for making art history approachable.",
        "reading_level": "early",
        "age_range": "5-9",
        "subjects": ["art", "biography", "art history"],
        "time_period": "19th century",
        "region": "Europe",
        "isbn": "9780516422763",
        "language": "English",
        "series": "Getting to Know the World's Greatest Artists",
        "popularity_score": 76,
        "page_count": 32,
        "publication_year": 1990,
        "publisher": "Children's Press",
    },
]

SOURCES = [
    {
        "name": "Amazon",
        "base_url": "https://www.amazon.com",
        "affiliate_tag": "livingbooks-20",
        "logo_url": "/images/sources/amazon.svg",
    },
    {
        "name": "BookShop.org",
        "base_url": "https://bookshop.org",
        "affiliate_tag": None,
        "logo_url": "/images/sources/bookshop.svg",
    },
    {
        "name": "ThriftBooks",
        "base_url": "https://www.thriftbooks.com",
        "affiliate_tag": None,
        "logo_url": "/images/sources/thriftbooks.svg",
    },
    {
        "name": "AbeBooks",
        "base_url": "https://www.abebooks.com",
        "affiliate_tag": None,
        "logo_url": "/images/sources/abebooks.svg",
    },
    {
        "name": "Library (WorldCat)",
        "base_url": "https://www.worldcat.org",
        "affiliate_tag": None,
        "logo_url": "/images/sources/library.svg",
    },
]

CURATED_LISTS = [
    {
        "name": "Charlotte Mason Essentials",
        "slug": "charlotte-mason-essentials",
        "description": "The living books most recommended by Charlotte Mason educators — books that bring subjects alive through literary storytelling rather than dry textbooks.",
        "category": "Philosophy",
        "is_featured": True,
        "book_titles": [
            "Charlotte's Web", "The Wind in the Willows", "Pilgrim's Progress",
            "The Handbook of Nature Study", "Understood Betsy", "Beautiful Stories from Shakespeare",
            "Paddle-to-the-Sea", "The Burgess Bird Book for Children",
        ],
    },
    {
        "name": "First Living Books (Ages 4-7)",
        "slug": "first-living-books",
        "description": "The perfect starting point for young children: picture books and read-alouds that spark wonder, imagination, and a love of learning.",
        "category": "By Age",
        "is_featured": True,
        "book_titles": [
            "Blueberries for Sal", "Make Way for Ducklings", "Ox-Cart Man",
            "Paddle-to-the-Sea", "The Burgess Bird Book for Children",
        ],
    },
    {
        "name": "Living History: Ancient World",
        "slug": "living-history-ancient",
        "description": "Travel back to ancient civilizations through stories that make history unforgettable — from Greek myths to biblical times.",
        "category": "History",
        "is_featured": True,
        "book_titles": [
            "The Story of the World, Volume 1: Ancient Times",
            "D'Aulaires' Book of Greek Myths", "The Bronze Bow",
            "The Story of Mankind",
        ],
    },
    {
        "name": "Living History: American Story",
        "slug": "living-history-america",
        "description": "Experience America's story through the eyes of those who lived it — from colonial days through the frontier and beyond.",
        "category": "History",
        "is_featured": True,
        "book_titles": [
            "Johnny Tremain", "Little House in the Big Woods", "Caddie Woodlawn",
            "The Witch of Blackbird Pond", "The Matchlock Gun", "Carry On, Mr. Bowditch",
            "This Country of Ours", "Amos Fortune, Free Man", "Little Britches: Father and I Were Ranchers",
        ],
    },
    {
        "name": "Nature Study Living Books",
        "slug": "nature-study",
        "description": "Books that cultivate a deep connection with the natural world — the foundation of Charlotte Mason's approach to science education.",
        "category": "Science & Nature",
        "is_featured": True,
        "book_titles": [
            "The Handbook of Nature Study", "The Burgess Bird Book for Children",
            "Pagoo", "Rascal", "Paddle-to-the-Sea", "Minn of the Mississippi",
            "Blueberries for Sal",
        ],
    },
    {
        "name": "Award Winners Hall of Fame",
        "slug": "award-winners",
        "description": "Newbery Medal and Honor winners that stand the test of time — books recognized as the finest in children's literature.",
        "category": "Awards",
        "is_featured": False,
        "book_titles": [
            "Carry On, Mr. Bowditch", "The Door in the Wall", "Island of the Blue Dolphins",
            "Number the Stars", "A Wrinkle in Time", "Johnny Tremain",
            "The Witch of Blackbird Pond", "The Bronze Bow", "The Wheel on the School",
            "King of the Wind", "Caddie Woodlawn",
        ],
    },
    {
        "name": "Adventure & Courage",
        "slug": "adventure-courage",
        "description": "Stories of bravery, perseverance, and daring that build character and ignite the imagination.",
        "category": "Character",
        "is_featured": False,
        "book_titles": [
            "Treasure Island", "Robin Hood", "The Hobbit",
            "Island of the Blue Dolphins", "Watership Down", "The Twenty-One Balloons",
            "Carry On, Mr. Bowditch",
        ],
    },
    {
        "name": "World Cultures & Geography",
        "slug": "world-cultures-geography",
        "description": "Living books that transport readers around the globe, building understanding and empathy for diverse peoples and places.",
        "category": "Geography",
        "is_featured": False,
        "book_titles": [
            "A Child's Geography of the World", "Heidi", "The Good Master",
            "The Wheel on the School", "The Trumpeter of Krakow",
            "Number the Stars", "King of the Wind",
        ],
    },
    {
        "name": "Timeless Fantasy & Imagination",
        "slug": "timeless-fantasy",
        "description": "The greatest fantasy and imaginative literature for young readers — stories that expand the mind and nourish the soul.",
        "category": "Literature",
        "is_featured": False,
        "book_titles": [
            "The Hobbit", "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
            "A Wrinkle in Time", "The Wind in the Willows", "Charlotte's Web",
            "Watership Down",
        ],
    },
    {
        "name": "Family Read-Alouds Everyone Loves",
        "slug": "family-read-alouds",
        "description": "The absolute best books for reading aloud together as a family — stories that captivate every age from 5 to 105.",
        "category": "Family",
        "is_featured": True,
        "book_titles": [
            "Charlotte's Web", "The Hobbit",
            "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
            "Little House in the Big Woods", "Where the Red Fern Grows",
            "Anne of Green Gables", "The Secret Garden", "The Wind in the Willows",
        ],
    },
    # === NEW LISTS ===
    {
        "name": "Living Science: How the World Works",
        "slug": "living-science",
        "description": "Science told through stories, biographies, and wonder — not textbooks. These books make the natural world and human discovery irresistible.",
        "category": "Science & Nature",
        "is_featured": True,
        "book_titles": [
            "The Story of Science: Aristotle Leads the Way",
            "Archimedes and the Door of Science", "The Mystery of the Periodic Table",
            "Fabre's Book of Insects", "The Handbook of Nature Study",
            "My Side of the Mountain", "The Burgess Bird Book for Children",
        ],
    },
    {
        "name": "Picture Books That Last a Lifetime",
        "slug": "picture-books-lifetime",
        "description": "The greatest picture books ever made — books your children will read to their children. Art, story, and meaning in perfect harmony.",
        "category": "By Age",
        "is_featured": True,
        "book_titles": [
            "Make Way for Ducklings", "Blueberries for Sal", "Madeline",
            "The Story of Ferdinand", "Mike Mulligan and His Steam Shovel",
            "The Little House", "Caps for Sale", "Millions of Cats", "Ox-Cart Man",
        ],
    },
    {
        "name": "Living Math: Numbers Come Alive",
        "slug": "living-math",
        "description": "Mathematics through story and wonder — because numbers are beautiful when you meet them as friends, not enemies.",
        "category": "Mathematics",
        "is_featured": False,
        "book_titles": [
            "The Life of Fred: Fractions", "Mathematician's Delight",
            "Archimedes and the Door of Science", "The Phantom Tollbooth",
            "Carry On, Mr. Bowditch",
        ],
    },
    {
        "name": "Poetry for the Whole Family",
        "slug": "poetry-family",
        "description": "Poetry collections that belong in every home — from nursery rhymes to Shakespeare, organized for families who want to fall in love with language.",
        "category": "Poetry & Language",
        "is_featured": False,
        "book_titles": [
            "A Child's Garden of Verses", "Favorite Poems Old and New",
            "Hailstones and Halibut Bones",
        ],
    },
    {
        "name": "Living History: Medieval World",
        "slug": "living-history-medieval",
        "description": "Knights, castles, cathedrals, and the people who built them — the Middle Ages through the eyes of those who lived it.",
        "category": "History",
        "is_featured": False,
        "book_titles": [
            "The Story of the World, Volume 2: The Middle Ages",
            "The Door in the Wall", "Adam of the Road", "Otto of the Silver Hand",
            "Men of Iron", "Robin Hood", "The Trumpeter of Krakow",
        ],
    },
    {
        "name": "Music & Art Appreciation",
        "slug": "music-art-appreciation",
        "description": "Living books that open children's eyes and ears to the great artists and composers — creativity as a way of seeing the world.",
        "category": "Arts",
        "is_featured": False,
        "book_titles": [
            "Sebastian Bach, The Boy from Thuringia", "Beethoven Lives Upstairs",
            "Getting to Know the World's Greatest Artists: Monet",
            "Discovering Great Artists", "Hailstones and Halibut Bones",
        ],
    },
    {
        "name": "Survival & Self-Reliance",
        "slug": "survival-self-reliance",
        "description": "Stories of humans against nature — building shelter, finding food, and discovering what you're truly made of.",
        "category": "Character",
        "is_featured": False,
        "book_titles": [
            "My Side of the Mountain", "Island of the Blue Dolphins",
            "Robinson Crusoe", "The Swiss Family Robinson",
            "Little Britches: Father and I Were Ranchers", "Rascal",
        ],
    },
    {
        "name": "The Complete Story of the World",
        "slug": "story-of-the-world-complete",
        "description": "Susan Wise Bauer's beloved four-volume narrative history — the backbone of thousands of homeschool programs worldwide.",
        "category": "History",
        "is_featured": True,
        "book_titles": [
            "The Story of the World, Volume 1: Ancient Times",
            "The Story of the World, Volume 2: The Middle Ages",
            "The Story of the World, Volume 3: Early Modern Times",
            "The Story of the World, Volume 4: The Modern Age",
        ],
    },
    {
        "name": "British Literature Classics",
        "slug": "british-classics",
        "description": "The crown jewels of English children's literature — from the Lake District to Narnia, these are the books that defined the genre.",
        "category": "Literature",
        "is_featured": False,
        "book_titles": [
            "The Wind in the Willows", "The Secret Garden", "The Railway Children",
            "Black Beauty", "Swallows and Amazons", "The Borrowers",
            "Treasure Island", "A Child's Garden of Verses",
        ],
    },
]


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        # Check if already fully seeded
        from sqlalchemy import select, func, delete
        book_count = (await session.execute(select(func.count(Book.id)))).scalar() or 0
        list_count = (await session.execute(select(func.count(CuratedList.id)))).scalar() or 0

        if book_count >= len(BOOKS) and list_count >= len(CURATED_LISTS):
            # Update cover images if any are missing
            missing_covers = (await session.execute(
                select(func.count(Book.id)).where(Book.cover_image_url.is_(None))
            )).scalar() or 0
            if missing_covers > 0:
                print(f"Updating {missing_covers} books with cover images...")
                books = (await session.execute(
                    select(Book).where(Book.cover_image_url.is_(None))
                )).scalars().all()
                for b in books:
                    if b.isbn:
                        b.cover_image_url = f"https://covers.openlibrary.org/b/isbn/{b.isbn}-L.jpg"
                await session.commit()
                print("Cover images updated!")
            else:
                print(f"Database already has {book_count} books and {list_count} lists. Skipping seed.")
            return

        # Clear partial data for clean re-seed
        if book_count > 0 or list_count > 0:
            print(f"Found partial data ({book_count} books, {list_count} lists). Clearing for clean seed...")
            await session.execute(delete(ListItem))
            await session.execute(delete(CuratedList))
            await session.execute(delete(BookLink))
            await session.execute(delete(Source))
            await session.execute(delete(Book))
            await session.commit()
            print("Cleared partial data.")

        # Insert books
        book_map = {}
        for data in BOOKS:
            book_data = dict(data)
            if not book_data.get("cover_image_url") and book_data.get("isbn"):
                book_data["cover_image_url"] = f"https://covers.openlibrary.org/b/isbn/{book_data['isbn']}-L.jpg"
            book = Book(**book_data)
            session.add(book)
            await session.flush()
            book_map[data["title"]] = book.id
        print(f"Inserted {len(BOOKS)} books.")

        # Insert sources
        source_map = {}
        for data in SOURCES:
            source = Source(**data)
            session.add(source)
            await session.flush()
            source_map[data["name"]] = source.id
        print(f"Inserted {len(SOURCES)} sources.")

        # Create links for each book to Amazon and BookShop
        link_count = 0
        amazon_id = source_map["Amazon"]
        bookshop_id = source_map["BookShop.org"]
        thrift_id = source_map["ThriftBooks"]
        library_id = source_map["Library (WorldCat)"]

        for title, book_id in book_map.items():
            book_data = next(b for b in BOOKS if b["title"] == title)
            isbn = book_data.get("isbn", "")

            # Amazon link
            session.add(BookLink(
                book_id=book_id,
                source_id=amazon_id,
                url=f"https://www.amazon.com/dp/{isbn}?tag=livingbooks-20" if isbn else f"https://www.amazon.com/s?k={title.replace(' ', '+')}",
                link_type="buy",
                affiliate_tag="livingbooks-20",
                price_hint="$8-15",
            ))
            link_count += 1

            # Bookshop link
            session.add(BookLink(
                book_id=book_id,
                source_id=bookshop_id,
                url=f"https://bookshop.org/p/books/{isbn}" if isbn else f"https://bookshop.org/books?keywords={title.replace(' ', '+')}",
                link_type="buy",
                price_hint="$10-18",
            ))
            link_count += 1

            # ThriftBooks link
            session.add(BookLink(
                book_id=book_id,
                source_id=thrift_id,
                url=f"https://www.thriftbooks.com/w/{title.lower().replace(' ', '-')}/",
                link_type="buy",
                price_hint="$3-8",
            ))
            link_count += 1

            # Library link
            if isbn:
                session.add(BookLink(
                    book_id=book_id,
                    source_id=library_id,
                    url=f"https://www.worldcat.org/isbn/{isbn}",
                    link_type="rent",
                    price_hint="Free",
                ))
                link_count += 1

        print(f"Created {link_count} book links.")

        # Create curated lists
        for lst_data in CURATED_LISTS:
            book_titles = lst_data.pop("book_titles")
            lst = CuratedList(**lst_data)
            session.add(lst)
            await session.flush()

            for rank, bt in enumerate(book_titles, start=1):
                if bt in book_map:
                    session.add(ListItem(
                        list_id=lst.id,
                        book_id=book_map[bt],
                        rank=rank,
                    ))
            await session.flush()

        print(f"Created {len(CURATED_LISTS)} curated lists.")
        await session.commit()
        print("Seed complete!")


if __name__ == "__main__":
    asyncio.run(seed())
